name: ${STACK_NAME:-www.notakrista.com}
networks:
  proxy:
    name: ${PROXY_NETWORK:-proxy}
    external: true
services:
  notakrista.com:
    image: ghcr.io/akrista/www.notakrista.com:latest
    container_name: notakrista
    build: .
    networks:
      - proxy
    ports:
      - 8000:8000
