<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

return new class extends Migration
{
    public function up(): void
    {
        $rawCards = [
            ['setcode' => 'CSOC-EN080', 'quantity' => 1],
            ['setcode' => '5DS1-EN040', 'quantity' => 1],
            ['setcode' => 'SDWS-EN037', 'quantity' => 2],
            ['setcode' => 'DP08-EN022', 'quantity' => 1],
            ['setcode' => 'ANPR-EN070', 'quantity' => 1],
            ['setcode' => 'LODT-EN076', 'quantity' => 1],
            ['setcode' => 'TDGS-EN077', 'quantity' => 1],
            ['setcode' => 'TDGS-EN078', 'quantity' => 1],
            ['setcode' => 'TDGS-EN071', 'quantity' => 3],
            ['setcode' => 'SDWS-EN036', 'quantity' => 2],
            ['setcode' => 'SDWS-EN035', 'quantity' => 2],
            ['setcode' => 'TDGS-EN067', 'quantity' => 4],
            ['setcode' => 'YS11-EN040', 'quantity' => 1],
            ['setcode' => 'DP09-EN027', 'quantity' => 1],
            ['setcode' => 'TDGS-EN075', 'quantity' => 2],
            ['setcode' => 'TDGS-EN068', 'quantity' => 4],
            ['setcode' => 'SOVR-EN076', 'quantity' => 2],
            ['setcode' => 'DP08-EN021', 'quantity' => 1],
            ['setcode' => 'TAEV-EN080', 'quantity' => 1],
            ['setcode' => 'TDGS-EN079', 'quantity' => 1],
            ['setcode' => 'PTDN-EN080', 'quantity' => 1],
            ['setcode' => 'SDGU-EN036', 'quantity' => 1],
            ['setcode' => 'SDGU-EN033', 'quantity' => 1],
            ['setcode' => 'SDGU-EN038', 'quantity' => 1],
            ['setcode' => 'SDGU-EN034', 'quantity' => 1],
            ['setcode' => 'SDGU-EN032', 'quantity' => 1],
            ['setcode' => 'SDGU-EN037', 'quantity' => 1],
            ['setcode' => 'SDGU-EN031', 'quantity' => 1],
            ['setcode' => 'SDGU-EN035', 'quantity' => 1],
            ['setcode' => 'YS11-EN039', 'quantity' => 1],
            ['setcode' => 'YS11-EN036', 'quantity' => 1],
            ['setcode' => 'YSDJ-EN038', 'quantity' => 1],
            ['setcode' => 'TDGS-EN066', 'quantity' => 4],
            ['setcode' => 'DP08-EN024', 'quantity' => 2],
            ['setcode' => 'DP08-EN028', 'quantity' => 1],
            ['setcode' => 'SD8-EN030', 'quantity' => 1],
            ['setcode' => 'YS11-EN035', 'quantity' => 1],
            ['setcode' => 'SYE-044', 'quantity' => 1],
            ['setcode' => '5DS1-EN039', 'quantity' => 1],
            ['setcode' => '5DS1-EN033', 'quantity' => 1],
            ['setcode' => '5DS2-EN039', 'quantity' => 1],
            ['setcode' => 'LOD-010', 'quantity' => 1],
            ['setcode' => 'SDZW-EN037', 'quantity' => 1],
            ['setcode' => 'FOTB-EN053', 'quantity' => 1],
            ['setcode' => 'IOC-EN107', 'quantity' => 1],
            ['setcode' => 'FOTB-EN051', 'quantity' => 1],
            ['setcode' => 'SD10-EN036', 'quantity' => 1],
            ['setcode' => 'SDK-034', 'quantity' => 1],
            ['setcode' => 'SDK-049', 'quantity' => 2],
            ['setcode' => 'SDK-047', 'quantity' => 1],
            ['setcode' => 'FOTB-EN052', 'quantity' => 1],
            ['setcode' => 'SOI-EN055', 'quantity' => 1],
            ['setcode' => 'IOC-EN108', 'quantity' => 1],
            ['setcode' => 'DP05-EN023', 'quantity' => 1],
            ['setcode' => 'SDK-038', 'quantity' => 1],
            ['setcode' => 'SDZW-EN035', 'quantity' => 1],
            ['setcode' => 'DP2-EN027', 'quantity' => 1],
            ['setcode' => 'SYE-048', 'quantity' => 1],
            ['setcode' => 'SOVR-EN075', 'quantity' => 1],
            ['setcode' => 'SOD-EN059', 'quantity' => 1],
            ['setcode' => '5DS2-EN035', 'quantity' => 1],
            ['setcode' => 'SD10-EN032', 'quantity' => 1],
            ['setcode' => 'SDK-050', 'quantity' => 1],
            ['setcode' => 'SDJ-047', 'quantity' => 1],
            ['setcode' => '5DS1-EN035', 'quantity' => 1],
            ['setcode' => 'SDWS-EN038', 'quantity' => 2],
            ['setcode' => 'LOD-014', 'quantity' => 1],
            ['setcode' => '5DS2-EN036', 'quantity' => 1],
            ['setcode' => 'YS11-EN037', 'quantity' => 1],
            ['setcode' => 'SYE-050', 'quantity' => 1],
            ['setcode' => 'SDMM-EN034', 'quantity' => 3],
            ['setcode' => 'SD10-EN035', 'quantity' => 1],
            ['setcode' => 'SDMM-EN031', 'quantity' => 3],
            ['setcode' => 'SDMM-EN033', 'quantity' => 3],
            ['setcode' => 'DR2-EN105', 'quantity' => 1],
            ['setcode' => 'SDMM-EN037', 'quantity' => 6],
            ['setcode' => 'SD10-EN037', 'quantity' => 1],
            ['setcode' => 'FOTB-EN058', 'quantity' => 1],
            ['setcode' => 'ABPF-EN076', 'quantity' => 2],
            ['setcode' => 'SDK-040', 'quantity' => 1],
            ['setcode' => 'YS11-EN033', 'quantity' => 1],
            ['setcode' => 'SDZW-EN033', 'quantity' => 1],
            ['setcode' => 'SD3-EN027', 'quantity' => 1],
            ['setcode' => '5DS2-EN034', 'quantity' => 1],
            ['setcode' => 'DPKB-EN0378', 'quantity' => 1],
            ['setcode' => 'CDIP-EN059', 'quantity' => 1],
            ['setcode' => 'DPKB-EN040', 'quantity' => 1],
            ['setcode' => 'ABPF-EN074', 'quantity' => 3],
            ['setcode' => 'ABPF-EN069', 'quantity' => 2],
            ['setcode' => 'ABPF-EN079', 'quantity' => 1],
            ['setcode' => 'ABPF-EN070', 'quantity' => 2],
            ['setcode' => 'ABPF-EN067', 'quantity' => 1],
            ['setcode' => 'ABPF-EN071', 'quantity' => 2],
            ['setcode' => 'YS11-EN032', 'quantity' => 1],
            ['setcode' => 'SOVR-EN073', 'quantity' => 1],
            ['setcode' => 'ABPF-EN075', 'quantity' => 3],
            ['setcode' => 'SOVR-EN072', 'quantity' => 1],
            ['setcode' => 'ABPF-EN066', 'quantity' => 2],
            ['setcode' => 'STBL-EN078', 'quantity' => 1],
            ['setcode' => 'YS11-EN031', 'quantity' => 1],
            ['setcode' => 'SDMM-EN036', 'quantity' => 3],
            ['setcode' => 'YS11-EN038', 'quantity' => 1],
            ['setcode' => 'STBL-EN073', 'quantity' => 1],
            ['setcode' => 'DP08-EN027', 'quantity' => 1],
            ['setcode' => 'TU02-EN016', 'quantity' => 1],
            ['setcode' => 'SDWS-EN034', 'quantity' => 2],
            ['setcode' => 'DCR-102', 'quantity' => 1],
            ['setcode' => 'SD10-EN033', 'quantity' => 1],
            ['setcode' => '5DS1-EN037', 'quantity' => 1],
            ['setcode' => 'LOD-078', 'quantity' => 1],
            ['setcode' => 'SOVR-EN066', 'quantity' => 1],
            ['setcode' => 'SDMM-EN026', 'quantity' => 3],
            ['setcode' => 'SOVR-EN064', 'quantity' => 3],
            ['setcode' => 'RGBT-EN059', 'quantity' => 2],
            ['setcode' => 'SD10-EN022', 'quantity' => 1],
            ['setcode' => '5DS2-EN040', 'quantity' => 1],
            ['setcode' => 'SOVR-EN055', 'quantity' => 2],
            ['setcode' => 'SOVR-EN071', 'quantity' => 2],
            ['setcode' => 'SDWS-EN028', 'quantity' => 2],
            ['setcode' => '5DS1-EN029', 'quantity' => 1],
            ['setcode' => 'STBL-EN066', 'quantity' => 1],
            ['setcode' => 'SDK-045', 'quantity' => 2],
            ['setcode' => 'SOVR-EN065', 'quantity' => 1],
            ['setcode' => 'SOVR-EN063', 'quantity' => 3],
            ['setcode' => '5DS2-EN022', 'quantity' => 1],
            ['setcode' => '5DS1-EN025', 'quantity' => 1],
            ['setcode' => '5DS2-EN028', 'quantity' => 1],
            ['setcode' => '5DS1-EN028', 'quantity' => 1],
            ['setcode' => 'SOVR-EN069', 'quantity' => 1],
            ['setcode' => 'SDZW-EN023', 'quantity' => 1],
            ['setcode' => 'SD10-EN021', 'quantity' => 1],
            ['setcode' => 'TDGS-EN091', 'quantity' => 1],
            ['setcode' => 'SD10-EN019', 'quantity' => 1],
            ['setcode' => 'TU02-EN015', 'quantity' => 1],
            ['setcode' => 'ABPF-EN057', 'quantity' => 2],
            ['setcode' => 'CRV-EN038', 'quantity' => 1],
            ['setcode' => 'DPKB-EN032', 'quantity' => 1],
            ['setcode' => 'SYE-027', 'quantity' => 1],
            ['setcode' => 'SDJ-027', 'quantity' => 1],
            ['setcode' => 'IOC-EN046', 'quantity' => 1],
            ['setcode' => 'SD3-EN018', 'quantity' => 1],
            ['setcode' => 'SDZW-EN020', 'quantity' => 1],
            ['setcode' => 'LOB-EN047', 'quantity' => 1],
            ['setcode' => 'DP10-EN022', 'quantity' => 1],
            ['setcode' => 'ABPF-EN058', 'quantity' => 3],
            ['setcode' => '5DS2-EN023', 'quantity' => 1],
            ['setcode' => 'SDJ-032', 'quantity' => 1],
            ['setcode' => 'TAEV-EN050', 'quantity' => 1],
            ['setcode' => 'SD3-EN017', 'quantity' => 1],
            ['setcode' => 'FOTB-EN043', 'quantity' => 1],
            ['setcode' => 'SD7-EN024', 'quantity' => 1],
            ['setcode' => 'SDZW-EN024', 'quantity' => 1],
            ['setcode' => 'SDK-048', 'quantity' => 3],
            ['setcode' => 'FOTB-EN038', 'quantity' => 1],
            ['setcode' => 'PSV-061', 'quantity' => 1],
            ['setcode' => 'SDZW-EN018', 'quantity' => 1],
            ['setcode' => 'SDJ-038', 'quantity' => 1],
            ['setcode' => 'TLM-EN043', 'quantity' => 1],
            ['setcode' => 'SD3-EN019', 'quantity' => 1],
            ['setcode' => 'DP09-EN019', 'quantity' => 1],
            ['setcode' => 'EEN-EN041', 'quantity' => 1],
            ['setcode' => 'SD10-EN027', 'quantity' => 1],
            ['setcode' => 'SDK-037', 'quantity' => 1],
            ['setcode' => 'SD5-EN027', 'quantity' => 1],
            ['setcode' => 'SDK-035', 'quantity' => 1],
            ['setcode' => 'SDJ-029', 'quantity' => 1],
            ['setcode' => 'SDGU-EN028', 'quantity' => 1],
            ['setcode' => 'SDZW-EN031', 'quantity' => 1],
            ['setcode' => 'SDJ-031', 'quantity' => 1],
            ['setcode' => '5DS2-EN031', 'quantity' => 1],
            ['setcode' => 'SKE-026', 'quantity' => 1],
            ['setcode' => 'SDK-023', 'quantity' => 1],
            ['setcode' => '5DS2-EN032', 'quantity' => 1],
            ['setcode' => 'SDWS-EN022', 'quantity' => 2],
            ['setcode' => '5DS2-EN030', 'quantity' => 1],
            ['setcode' => 'SDWS-EN020', 'quantity' => 2],
            ['setcode' => '5DS1-EN022', 'quantity' => 1],
            ['setcode' => '5DS2-EN026', 'quantity' => 2],
            ['setcode' => 'SDMM-EN022', 'quantity' => 3],
            ['setcode' => '5DS2-EN021', 'quantity' => 1],
            ['setcode' => 'YS11-EN026', 'quantity' => 1],
            ['setcode' => 'SYE-039', 'quantity' => 1],
            ['setcode' => 'SDMM-EN023', 'quantity' => 2],
            ['setcode' => 'SD3-EN020', 'quantity' => 1],
            ['setcode' => '5DS2-EN024', 'quantity' => 1],
            ['setcode' => 'FOTB-EN040', 'quantity' => 1],
            ['setcode' => 'SDWS-EN027', 'quantity' => 2],
            ['setcode' => 'DCR-034', 'quantity' => 1],
            ['setcode' => 'SDMM-EN029', 'quantity' => 3],
            ['setcode' => 'SDMM-EN027', 'quantity' => 1],
            ['setcode' => 'SDMM-EN021', 'quantity' => 3],
            ['setcode' => 'SDMM-EN028', 'quantity' => 2],
            ['setcode' => 'YS11-EN029', 'quantity' => 1],
            ['setcode' => 'ABPF-EN056', 'quantity' => 1],
            ['setcode' => 'SDK-020', 'quantity' => 1],
            ['setcode' => 'EOJ-EN041', 'quantity' => 1],
            ['setcode' => 'MFC-036', 'quantity' => 1],
            ['setcode' => 'DCR-036', 'quantity' => 1],
            ['setcode' => 'TAEV-EN062', 'quantity' => 1],
            ['setcode' => 'SKE-032', 'quantity' => 1],
            ['setcode' => 'SYE-030', 'quantity' => 1],
            ['setcode' => 'SDJ-030', 'quantity' => 1],
            ['setcode' => 'ABPF-EN054', 'quantity' => 4],
            ['setcode' => 'SDZW-EN029', 'quantity' => 1],
            ['setcode' => 'LODT-EN056', 'quantity' => 1],
            ['setcode' => 'GLAS-EN053', 'quantity' => 1],
            ['setcode' => 'ABPF-EN052', 'quantity' => 1],
            ['setcode' => 'SDZW-EN028', 'quantity' => 1],
            ['setcode' => 'FOTB-EN042', 'quantity' => 1],
            ['setcode' => 'ABPF-EN049', 'quantity' => 1],
            ['setcode' => 'SDZW-EN022', 'quantity' => 1],
            ['setcode' => '5DS2-EN027', 'quantity' => 1],
            ['setcode' => 'ABPF-EN050', 'quantity' => 2],
            ['setcode' => 'PGD-090', 'quantity' => 1],
            ['setcode' => 'SD09-EN024', 'quantity' => 1],
            ['setcode' => 'TAEV-EN024', 'quantity' => 1],
            ['setcode' => 'SOVR-EN061', 'quantity' => 2],
            ['setcode' => 'ABPF-EN046', 'quantity' => 3],
            ['setcode' => 'SOVR-EN062', 'quantity' => 1],
            ['setcode' => 'ABPF-EN047', 'quantity' => 3],
            ['setcode' => 'TU02-EN014', 'quantity' => 1],
            ['setcode' => 'SOVR-EN048', 'quantity' => 1],
            ['setcode' => 'YS11-EN028', 'quantity' => 1],
            ['setcode' => 'SDK-032', 'quantity' => 2],
            ['setcode' => 'YS11-EN025', 'quantity' => 1],
            ['setcode' => 'DP09-EN021', 'quantity' => 2],
            ['setcode' => 'ABPF-EN048', 'quantity' => 3],
            ['setcode' => 'DP09-EN020', 'quantity' => 1],
            ['setcode' => 'SOVR-EN059', 'quantity' => 1],
            ['setcode' => 'SDWS-EN031', 'quantity' => 2],
            ['setcode' => 'SOVR-EN050', 'quantity' => 1],
            ['setcode' => 'SOVR-EN049', 'quantity' => 1],
            ['setcode' => 'TU01-EN013', 'quantity' => 1],
            ['setcode' => 'SDGU-EN029', 'quantity' => 1],
            ['setcode' => 'SDZW-EN025', 'quantity' => 1],
            ['setcode' => 'TDGS-EN057', 'quantity' => 4],
            ['setcode' => 'DP08-EN017', 'quantity' => 1],
            ['setcode' => 'TDGS-EN056', 'quantity' => 2],
            ['setcode' => 'CSOC-EN053', 'quantity' => 1],
            ['setcode' => 'TDGS-EN055', 'quantity' => 2],
            ['setcode' => 'CSOC-EN046', 'quantity' => 1],
            ['setcode' => 'SDGU-EN023', 'quantity' => 1],
            ['setcode' => 'TDGS-EN047', 'quantity' => 1],
            ['setcode' => 'YS11-EN023', 'quantity' => 1],
            ['setcode' => 'SDGU-EN027', 'quantity' => 1],
            ['setcode' => 'SDGU-EN024', 'quantity' => 1],
            ['setcode' => 'YS11-EN022', 'quantity' => 1],
            ['setcode' => 'SDGU-EN026', 'quantity' => 1],
            ['setcode' => 'TDGS-EN054', 'quantity' => 2],
            ['setcode' => 'SDGU-EN030', 'quantity' => 1],
            ['setcode' => 'TDGS-EN050', 'quantity' => 3],
            ['setcode' => 'SDGU-EN025', 'quantity' => 2],
            ['setcode' => 'TDGS-EN061', 'quantity' => 2],
        ];

        $aggregated = [];
        foreach ($rawCards as $card) {
            $key = mb_strtoupper(mb_trim($card['setcode']));
            if (isset($aggregated[$key])) {
                $aggregated[$key]['quantity'] += (int) $card['quantity'];
            } else {
                $aggregated[$key] = [
                    'setcode' => $key,
                    'quantity' => (int) $card['quantity'],
                ];
            }
        }

        $now = now();
        foreach ($aggregated as $card) {
            $existing = DB::table('yugioh_cards')->where('setcode', $card['setcode'])->first();
            if ($existing) {
                DB::table('yugioh_cards')->where('id', $existing->id)->update([
                    'quantity' => $existing->quantity + $card['quantity'],
                    'updated_at' => $now,
                ]);
            } else {
                DB::table('yugioh_cards')->insert([
                    'id' => (string) Str::uuid(),
                    'setcode' => $card['setcode'],
                    'quantity' => $card['quantity'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }
    }

    public function down(): void {}
};
