<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('yugioh_cards', function (Blueprint $table): void {
            $table->string('id', 36)->primary();
            $table->string('setcode', 20)->unique();
            $table->unsignedInteger('quantity')->default(1);
            $table->boolean('is_sold')->default(false);
            $table->string('name')->nullable();
            $table->string('type')->nullable();
            $table->string('frame_type')->nullable();
            $table->string('rarity')->nullable();
            $table->decimal('price', 8, 2)->nullable();
            $table->decimal('card_price', 8, 2)->nullable();
            $table->string('image_url', 2048)->nullable();
            $table->unsignedInteger('ygoprodeck_id')->nullable();
            $table->timestamps();
            $table->softDeletes();
            $table->userstampsUuid();
            $table->userstampsUuidSoftDeletes();

            $table->index('setcode', 'yugioh_cards_setcode_index');
        });

        $rawCards = [
            ['setcode' => '5DS1-EN001', 'quantity' => 1],
            ['setcode' => '5DS1-EN002', 'quantity' => 1],
            ['setcode' => '5DS1-EN003', 'quantity' => 1],
            ['setcode' => '5DS1-EN004', 'quantity' => 1],
            ['setcode' => '5DS1-EN005', 'quantity' => 1],
            ['setcode' => '5DS1-EN006', 'quantity' => 1],
            ['setcode' => '5DS1-EN007', 'quantity' => 1],
            ['setcode' => '5DS1-EN008', 'quantity' => 1],
            ['setcode' => '5DS1-EN009', 'quantity' => 1],
            ['setcode' => '5DS1-EN010', 'quantity' => 1],
            ['setcode' => '5DS1-EN011', 'quantity' => 1],
            ['setcode' => '5DS1-EN012', 'quantity' => 1],
            ['setcode' => '5DS1-EN014', 'quantity' => 1],
            ['setcode' => '5DS1-EN015', 'quantity' => 1],
            ['setcode' => '5DS1-EN016', 'quantity' => 1],
            ['setcode' => '5DS1-EN018', 'quantity' => 1],
            ['setcode' => '5DS1-EN021', 'quantity' => 1],
            ['setcode' => '5DS1-EN023', 'quantity' => 1],
            ['setcode' => '5DS1-EN026', 'quantity' => 1],
            ['setcode' => '5DS1-EN027', 'quantity' => 1],
            ['setcode' => '5DS1-EN030', 'quantity' => 1],
            ['setcode' => '5DS1-EN036', 'quantity' => 1],
            ['setcode' => '5DS1-EN041', 'quantity' => 1],
            ['setcode' => '5DS1-EN042', 'quantity' => 1],
            ['setcode' => '5DS1-EN043', 'quantity' => 1],
            ['setcode' => '5DS2-EN001', 'quantity' => 1],
            ['setcode' => '5DS2-EN002', 'quantity' => 1],
            ['setcode' => '5DS2-EN003', 'quantity' => 1],
            ['setcode' => '5DS2-EN005', 'quantity' => 1],
            ['setcode' => '5DS2-EN006', 'quantity' => 1],
            ['setcode' => '5DS2-EN007', 'quantity' => 1],
            ['setcode' => '5DS2-EN008', 'quantity' => 1],
            ['setcode' => '5DS2-EN009', 'quantity' => 1],
            ['setcode' => '5DS2-EN010', 'quantity' => 1],
            ['setcode' => '5DS2-EN011', 'quantity' => 1],
            ['setcode' => '5DS2-EN012', 'quantity' => 1],
            ['setcode' => '5DS2-EN013', 'quantity' => 1],
            ['setcode' => '5DS2-EN015', 'quantity' => 2],
            ['setcode' => '5DS2-EN016', 'quantity' => 1],
            ['setcode' => '5DS2-EN017', 'quantity' => 1],
            ['setcode' => '5DS2-EN020', 'quantity' => 1],
            ['setcode' => '5DS2-EN025', 'quantity' => 1],
            ['setcode' => '5DS2-EN029', 'quantity' => 1],
            ['setcode' => '5DS2-EN041', 'quantity' => 1],
            ['setcode' => '5DS2-EN042', 'quantity' => 1],
            ['setcode' => '5DS2-EN043', 'quantity' => 1],
            ['setcode' => 'ABPF-EN001', 'quantity' => 3],
            ['setcode' => 'ABPF-EN002', 'quantity' => 2],
            ['setcode' => 'ABPF-EN003', 'quantity' => 2],
            ['setcode' => 'ABPF-EN007', 'quantity' => 4],
            ['setcode' => 'ABPF-EN008', 'quantity' => 1],
            ['setcode' => 'ABPF-EN009', 'quantity' => 3],
            ['setcode' => 'ABPF-EN011', 'quantity' => 4],
            ['setcode' => 'ABPF-EN013', 'quantity' => 2],
            ['setcode' => 'ABPF-EN015', 'quantity' => 4],
            ['setcode' => 'ABPF-EN016', 'quantity' => 1],
            ['setcode' => 'ABPF-EN017', 'quantity' => 1],
            ['setcode' => 'ABPF-EN020', 'quantity' => 4],
            ['setcode' => 'ABPF-EN022', 'quantity' => 3],
            ['setcode' => 'ABPF-EN023', 'quantity' => 4],
            ['setcode' => 'ABPF-EN024', 'quantity' => 2],
            ['setcode' => 'ABPF-EN029', 'quantity' => 2],
            ['setcode' => 'ABPF-EN030', 'quantity' => 1],
            ['setcode' => 'ABPF-EN031', 'quantity' => 3],
            ['setcode' => 'ABPF-EN032', 'quantity' => 1],
            ['setcode' => 'ABPF-EN034', 'quantity' => 3],
            ['setcode' => 'ABPF-EN035', 'quantity' => 1],
            ['setcode' => 'ABPF-EN036', 'quantity' => 2],
            ['setcode' => 'ABPF-EN051', 'quantity' => 1],
            ['setcode' => 'ABPF-EN059', 'quantity' => 1],
            ['setcode' => 'ABPF-EN063', 'quantity' => 3],
            ['setcode' => 'ABPF-EN068', 'quantity' => 2],
            ['setcode' => 'ABPF-EN072', 'quantity' => 1],
            ['setcode' => 'ABPF-EN090', 'quantity' => 1],
            ['setcode' => 'ABPF-EN091', 'quantity' => 1],
            ['setcode' => 'ABPF-EN092', 'quantity' => 1],
            ['setcode' => 'ABPF-EN093', 'quantity' => 1],
            ['setcode' => 'ANPR-EN023', 'quantity' => 1],
            ['setcode' => 'AST-029', 'quantity' => 1],
            ['setcode' => 'CRV-EN009', 'quantity' => 1],
            ['setcode' => 'CSOC-EN004', 'quantity' => 1],
            ['setcode' => 'CSOC-EN010', 'quantity' => 1],
            ['setcode' => 'CSOC-EN012', 'quantity' => 1],
            ['setcode' => 'CSOC-EN018', 'quantity' => 1],
            ['setcode' => 'CSOC-EN019', 'quantity' => 1],
            ['setcode' => 'CSOC-EN023', 'quantity' => 1],
            ['setcode' => 'CSOC-EN024', 'quantity' => 1],
            ['setcode' => 'CSOC-EN025', 'quantity' => 1],
            ['setcode' => 'CSOC-EN032', 'quantity' => 1],
            ['setcode' => 'CSOC-EN033', 'quantity' => 1],
            ['setcode' => 'CSOC-EN068', 'quantity' => 1],
            ['setcode' => 'CSOC-EN070', 'quantity' => 1],
            ['setcode' => 'CSOC-EN075', 'quantity' => 2],
            ['setcode' => 'CSOC-EN076', 'quantity' => 1],
            ['setcode' => 'CSOC-EN082', 'quantity' => 1],
            ['setcode' => 'CT06-EN001', 'quantity' => 1],
            ['setcode' => 'DB1-EN094', 'quantity' => 1],
            ['setcode' => 'DB2-EN129', 'quantity' => 1],
            ['setcode' => 'DLG1-EN068', 'quantity' => 1],
            ['setcode' => 'DP06-EN005', 'quantity' => 1],
            ['setcode' => 'DP08-EN002', 'quantity' => 2],
            ['setcode' => 'DP08-EN004', 'quantity' => 1],
            ['setcode' => 'DP08-EN007', 'quantity' => 1],
            ['setcode' => 'DP08-EN008', 'quantity' => 2],
            ['setcode' => 'DP08-EN009', 'quantity' => 1],
            ['setcode' => 'DP08-EN015', 'quantity' => 1],
            ['setcode' => 'DP08-EN026', 'quantity' => 2],
            ['setcode' => 'DP08-EN029', 'quantity' => 1],
            ['setcode' => 'DP08-EN04', 'quantity' => 1],
            ['setcode' => 'DP08-EN08', 'quantity' => 1],
            ['setcode' => 'DP08-EN10', 'quantity' => 1],
            ['setcode' => 'DP09-EN002', 'quantity' => 1],
            ['setcode' => 'DP09-EN005', 'quantity' => 1],
            ['setcode' => 'DP09-EN008', 'quantity' => 2],
            ['setcode' => 'DP09-EN009', 'quantity' => 1],
            ['setcode' => 'DP09-EN010', 'quantity' => 1],
            ['setcode' => 'DP09-EN011', 'quantity' => 1],
            ['setcode' => 'DP09-EN012', 'quantity' => 2],
            ['setcode' => 'DP09-EN015', 'quantity' => 2],
            ['setcode' => 'DP09-EN02', 'quantity' => 2],
            ['setcode' => 'DP09-EN022', 'quantity' => 1],
            ['setcode' => 'DP09-EN023', 'quantity' => 2],
            ['setcode' => 'DP09-EN04', 'quantity' => 2],
            ['setcode' => 'DP10-EN003', 'quantity' => 1],
            ['setcode' => 'DP10-EN009', 'quantity' => 1],
            ['setcode' => 'DP10-EN018', 'quantity' => 1],
            ['setcode' => 'DP10-EN07', 'quantity' => 1],
            ['setcode' => 'DP1-EN014', 'quantity' => 2],
            ['setcode' => 'DPKB-EN003', 'quantity' => 1],
            ['setcode' => 'DPKB-EN006', 'quantity' => 1],
            ['setcode' => 'DPKB-EN011', 'quantity' => 1],
            ['setcode' => 'DPKB-EN013', 'quantity' => 2],
            ['setcode' => 'DPKB-EN014', 'quantity' => 1],
            ['setcode' => 'DPKB-EN021', 'quantity' => 1],
            ['setcode' => 'DPKB-EN024', 'quantity' => 1],
            ['setcode' => 'DPKB-EN03', 'quantity' => 1],
            ['setcode' => 'DPKB-EN07', 'quantity' => 1],
            ['setcode' => 'EEN-EN005', 'quantity' => 1],
            ['setcode' => 'EEN-EN013', 'quantity' => 1],
            ['setcode' => 'FET-EN052', 'quantity' => 1],
            ['setcode' => 'FOTB-EN027', 'quantity' => 1],
            ['setcode' => 'FOTB-EN037', 'quantity' => 1],
            ['setcode' => 'FOTB-ENSE1', 'quantity' => 1],
            ['setcode' => 'GLAS-EN027', 'quantity' => 1],
            ['setcode' => 'GLAS-EN029', 'quantity' => 3],
            ['setcode' => 'GLAS-EN042', 'quantity' => 3],
            ['setcode' => 'GLD1-EN036', 'quantity' => 1],
            ['setcode' => 'IOC-EN004', 'quantity' => 1],
            ['setcode' => 'IOC-EN011', 'quantity' => 1],
            ['setcode' => 'IOC-EN059', 'quantity' => 1],
            ['setcode' => 'IOC-EN081', 'quantity' => 1],
            ['setcode' => 'LOB-012', 'quantity' => 1],
            ['setcode' => 'LOB-014', 'quantity' => 1],
            ['setcode' => 'LOB-073', 'quantity' => 1],
            ['setcode' => 'LOB-079', 'quantity' => 1],
            ['setcode' => 'LODT-EN004', 'quantity' => 1],
            ['setcode' => 'LODT-EN009', 'quantity' => 1],
            ['setcode' => 'LODT-EN012', 'quantity' => 1],
            ['setcode' => 'LODT-EN027', 'quantity' => 3],
            ['setcode' => 'LODT-EN047', 'quantity' => 1],
            ['setcode' => 'LODT-EN057', 'quantity' => 1],
            ['setcode' => 'LODT-EN061', 'quantity' => 1],
            ['setcode' => 'LODT-EN068', 'quantity' => 1],
            ['setcode' => 'LON-033', 'quantity' => 1],
            ['setcode' => 'LON-054', 'quantity' => 1],
            ['setcode' => 'MOV-EN002', 'quantity' => 1],
            ['setcode' => 'PGD-018', 'quantity' => 1],
            ['setcode' => 'PGD-024', 'quantity' => 1],
            ['setcode' => 'PGD-028', 'quantity' => 1],
            ['setcode' => 'PP02-EN004', 'quantity' => 1],
            ['setcode' => 'PSV-057', 'quantity' => 1],
            ['setcode' => 'PSV-059', 'quantity' => 1],
            ['setcode' => 'PTDN-EN014', 'quantity' => 1],
            ['setcode' => 'PTDN-EN023', 'quantity' => 1],
            ['setcode' => 'PTDN-EN025', 'quantity' => 1],
            ['setcode' => 'PTDN-EN026', 'quantity' => 2],
            ['setcode' => 'PTDN-EN032', 'quantity' => 1],
            ['setcode' => 'PTDN-EN035', 'quantity' => 1],
            ['setcode' => 'PTDN-EN040', 'quantity' => 1],
            ['setcode' => 'PTDN-EN042', 'quantity' => 1],
            ['setcode' => 'PTDN-EN051', 'quantity' => 1],
            ['setcode' => 'PTDN-EN057', 'quantity' => 1],
            ['setcode' => 'PTDN-EN085', 'quantity' => 1],
            ['setcode' => 'RDS-EN020', 'quantity' => 1],
            ['setcode' => 'RDS-EN034', 'quantity' => 1],
            ['setcode' => 'SD09-EN015', 'quantity' => 1],
            ['setcode' => 'SD09-EN033', 'quantity' => 1],
            ['setcode' => 'SD10-EN002', 'quantity' => 1],
            ['setcode' => 'SD10-EN003', 'quantity' => 1],
            ['setcode' => 'SD10-EN004', 'quantity' => 1],
            ['setcode' => 'SD10-EN005', 'quantity' => 1],
            ['setcode' => 'SD10-EN006', 'quantity' => 1],
            ['setcode' => 'SD10-EN007', 'quantity' => 1],
            ['setcode' => 'SD10-EN008', 'quantity' => 1],
            ['setcode' => 'SD10-EN009', 'quantity' => 1],
            ['setcode' => 'SD10-EN011', 'quantity' => 1],
            ['setcode' => 'SD10-EN012', 'quantity' => 1],
            ['setcode' => 'SD10-EN013', 'quantity' => 1],
            ['setcode' => 'SD10-EN014', 'quantity' => 1],
            ['setcode' => 'SD10-EN015', 'quantity' => 2],
            ['setcode' => 'SD10-EN016', 'quantity' => 1],
            ['setcode' => 'SD10-EN017', 'quantity' => 1],
            ['setcode' => 'SD10-EN018', 'quantity' => 1],
            ['setcode' => 'SD10-EN020', 'quantity' => 1],
            ['setcode' => 'SD10-EN023', 'quantity' => 1],
            ['setcode' => 'SD10-EN024', 'quantity' => 1],
            ['setcode' => 'SD10-EN025', 'quantity' => 2],
            ['setcode' => 'SD10-EN028', 'quantity' => 1],
            ['setcode' => 'SD10-EN031', 'quantity' => 1],
            ['setcode' => 'SD10-EN034', 'quantity' => 1],
            ['setcode' => 'SD3-EN006', 'quantity' => 1],
            ['setcode' => 'SD3-EN007', 'quantity' => 1],
            ['setcode' => 'SD3-EN008', 'quantity' => 2],
            ['setcode' => 'SD3-EN011', 'quantity' => 1],
            ['setcode' => 'SD3-EN012', 'quantity' => 1],
            ['setcode' => 'SD3-EN016', 'quantity' => 1],
            ['setcode' => 'SD5-EN001', 'quantity' => 1],
            ['setcode' => 'SD5-EN002', 'quantity' => 1],
            ['setcode' => 'SD5-EN011', 'quantity' => 1],
            ['setcode' => 'SD5-EN012', 'quantity' => 1],
            ['setcode' => 'SD6-EN010', 'quantity' => 1],
            ['setcode' => 'SD6-EN022', 'quantity' => 2],
            ['setcode' => 'SD7-EN015', 'quantity' => 1],
            ['setcode' => 'SDGU-EN001', 'quantity' => 1],
            ['setcode' => 'SDGU-EN002', 'quantity' => 1],
            ['setcode' => 'SDGU-EN003', 'quantity' => 1],
            ['setcode' => 'SDGU-EN004', 'quantity' => 1],
            ['setcode' => 'SDGU-EN005', 'quantity' => 1],
            ['setcode' => 'SDGU-EN006', 'quantity' => 1],
            ['setcode' => 'SDGU-EN007', 'quantity' => 1],
            ['setcode' => 'SDGU-EN008', 'quantity' => 1],
            ['setcode' => 'SDGU-EN009', 'quantity' => 1],
            ['setcode' => 'SDGU-EN010', 'quantity' => 1],
            ['setcode' => 'SDGU-EN011', 'quantity' => 1],
            ['setcode' => 'SDGU-EN012', 'quantity' => 1],
            ['setcode' => 'SDGU-EN013', 'quantity' => 1],
            ['setcode' => 'SDGU-EN014', 'quantity' => 1],
            ['setcode' => 'SDGU-EN015', 'quantity' => 1],
            ['setcode' => 'SDGU-EN016', 'quantity' => 1],
            ['setcode' => 'SDGU-EN017', 'quantity' => 1],
            ['setcode' => 'SDGU-EN018', 'quantity' => 1],
            ['setcode' => 'SDGU-EN019', 'quantity' => 1],
            ['setcode' => 'SDGU-EN020', 'quantity' => 1],
            ['setcode' => 'SDGU-EN021', 'quantity' => 1],
            ['setcode' => 'SDGU-EN022', 'quantity' => 1],
            ['setcode' => 'SDGU-EN039', 'quantity' => 1],
            ['setcode' => 'SDJ-002', 'quantity' => 1],
            ['setcode' => 'SDJ-006', 'quantity' => 1],
            ['setcode' => 'SDJ-009', 'quantity' => 1],
            ['setcode' => 'SDJ-010', 'quantity' => 1],
            ['setcode' => 'SDJ-011', 'quantity' => 1],
            ['setcode' => 'SDJ-013', 'quantity' => 1],
            ['setcode' => 'SDJ-016', 'quantity' => 1],
            ['setcode' => 'SDJ-022', 'quantity' => 1],
            ['setcode' => 'SDJ-025', 'quantity' => 1],
            ['setcode' => 'SDJ-035', 'quantity' => 1],
            ['setcode' => 'SDJ-036', 'quantity' => 1],
            ['setcode' => 'SDJ-041', 'quantity' => 1],
            ['setcode' => 'SDK-002', 'quantity' => 1],
            ['setcode' => 'SDK-003', 'quantity' => 1],
            ['setcode' => 'SDK-004', 'quantity' => 1],
            ['setcode' => 'SDK-005', 'quantity' => 1],
            ['setcode' => 'SDK-006', 'quantity' => 1],
            ['setcode' => 'SDK-007', 'quantity' => 1],
            ['setcode' => 'SDK-008', 'quantity' => 2],
            ['setcode' => 'SDK-009', 'quantity' => 1],
            ['setcode' => 'SDK-010', 'quantity' => 1],
            ['setcode' => 'SDK-011', 'quantity' => 2],
            ['setcode' => 'SDK-012', 'quantity' => 1],
            ['setcode' => 'SDK-013', 'quantity' => 1],
            ['setcode' => 'SDK-014', 'quantity' => 1],
            ['setcode' => 'SDK-015', 'quantity' => 1],
            ['setcode' => 'SDK-016', 'quantity' => 1],
            ['setcode' => 'SDK-017', 'quantity' => 1],
            ['setcode' => 'SDK-018', 'quantity' => 1],
            ['setcode' => 'SDK-019', 'quantity' => 1],
            ['setcode' => 'SDK-022', 'quantity' => 1],
            ['setcode' => 'SDK-024', 'quantity' => 1],
            ['setcode' => 'SDK-026', 'quantity' => 1],
            ['setcode' => 'SDK-027', 'quantity' => 1],
            ['setcode' => 'SDK-028', 'quantity' => 1],
            ['setcode' => 'SDK-029', 'quantity' => 1],
            ['setcode' => 'SDK-030', 'quantity' => 1],
            ['setcode' => 'SDK-031', 'quantity' => 1],
            ['setcode' => 'SDK-033', 'quantity' => 2],
            ['setcode' => 'SDK-041', 'quantity' => 1],
            ['setcode' => 'SDK-042', 'quantity' => 1],
            ['setcode' => 'SDK-043', 'quantity' => 2],
            ['setcode' => 'SDK-044', 'quantity' => 1],
            ['setcode' => 'SDK-046', 'quantity' => 1],
            ['setcode' => 'SDMM-EN011', 'quantity' => 3],
            ['setcode' => 'SDMM-EN003', 'quantity' => 3],
            ['setcode' => 'SDMM-EN004', 'quantity' => 3],
            ['setcode' => 'SDMM-EN005', 'quantity' => 3],
            ['setcode' => 'SDMM-EN006', 'quantity' => 3],
            ['setcode' => 'SDMM-EN007', 'quantity' => 3],
            ['setcode' => 'SDMM-EN008', 'quantity' => 3],
            ['setcode' => 'SDMM-EN009', 'quantity' => 3],
            ['setcode' => 'SDMM-EN010', 'quantity' => 3],
            ['setcode' => 'SDMM-EN012', 'quantity' => 6],
            ['setcode' => 'SDMM-EN014', 'quantity' => 3],
            ['setcode' => 'SDMM-EN015', 'quantity' => 3],
            ['setcode' => 'SDMM-EN016', 'quantity' => 3],
            ['setcode' => 'SDMM-EN017', 'quantity' => 3],
            ['setcode' => 'SDMM-EN018', 'quantity' => 6],
            ['setcode' => 'SDMM-EN020', 'quantity' => 3],
            ['setcode' => 'SDMM-EN025', 'quantity' => 3],
            ['setcode' => 'SDMM-EN035', 'quantity' => 3],
            ['setcode' => 'SDP-005', 'quantity' => 1],
            ['setcode' => 'SDWS-EN001', 'quantity' => 3],
            ['setcode' => 'SDWS-EN002', 'quantity' => 3],
            ['setcode' => 'SDWS-EN003', 'quantity' => 2],
            ['setcode' => 'SDWS-EN004', 'quantity' => 1],
            ['setcode' => 'SDWS-EN006', 'quantity' => 2],
            ['setcode' => 'SDWS-EN007', 'quantity' => 2],
            ['setcode' => 'SDWS-EN008', 'quantity' => 2],
            ['setcode' => 'SDWS-EN009', 'quantity' => 2],
            ['setcode' => 'SDWS-EN011', 'quantity' => 3],
            ['setcode' => 'SDWS-EN012', 'quantity' => 4],
            ['setcode' => 'SDWS-EN013', 'quantity' => 2],
            ['setcode' => 'SDWS-EN014', 'quantity' => 1],
            ['setcode' => 'SDWS-EN015', 'quantity' => 2],
            ['setcode' => 'SDWS-EN016', 'quantity' => 2],
            ['setcode' => 'SDWS-EN017', 'quantity' => 3],
            ['setcode' => 'SDWS-EN019', 'quantity' => 1],
            ['setcode' => 'SDWS-EN021', 'quantity' => 1],
            ['setcode' => 'SDWS-EN023', 'quantity' => 2],
            ['setcode' => 'SDWS-EN024', 'quantity' => 2],
            ['setcode' => 'SDWS-EN025', 'quantity' => 1],
            ['setcode' => 'SDWS-EN029', 'quantity' => 2],
            ['setcode' => 'SDWS-EN030', 'quantity' => 2],
            ['setcode' => 'SDWS-EN033', 'quantity' => 2],
            ['setcode' => 'SDY-009', 'quantity' => 1],
            ['setcode' => 'SDY-011', 'quantity' => 1],
            ['setcode' => 'SDY-016', 'quantity' => 1],
            ['setcode' => 'SDY-030', 'quantity' => 1],
            ['setcode' => 'SDY-033', 'quantity' => 1],
            ['setcode' => 'SDY-046', 'quantity' => 1],
            ['setcode' => 'SDZW-EN001', 'quantity' => 1],
            ['setcode' => 'SDZW-EN002', 'quantity' => 1],
            ['setcode' => 'SDZW-EN003', 'quantity' => 1],
            ['setcode' => 'SDZW-EN004', 'quantity' => 1],
            ['setcode' => 'SDZW-EN006', 'quantity' => 1],
            ['setcode' => 'SDZW-EN007', 'quantity' => 2],
            ['setcode' => 'SDZW-EN008', 'quantity' => 1],
            ['setcode' => 'SDZW-EN009', 'quantity' => 1],
            ['setcode' => 'SDZW-EN010', 'quantity' => 1],
            ['setcode' => 'SDZW-EN011', 'quantity' => 1],
            ['setcode' => 'SDZW-EN012', 'quantity' => 3],
            ['setcode' => 'SDZW-EN013', 'quantity' => 1],
            ['setcode' => 'SDZW-EN014', 'quantity' => 1],
            ['setcode' => 'SDZW-EN015', 'quantity' => 1],
            ['setcode' => 'SDZW-EN030', 'quantity' => 1],
            ['setcode' => 'SDZW-EN036', 'quantity' => 1],
            ['setcode' => 'SKE-008', 'quantity' => 1],
            ['setcode' => 'SKE-018', 'quantity' => 1],
            ['setcode' => 'SOD-EN017', 'quantity' => 1],
            ['setcode' => 'SOI-EN012', 'quantity' => 2],
            ['setcode' => 'SOVR-EN004', 'quantity' => 3],
            ['setcode' => 'SOVR-EN013', 'quantity' => 1],
            ['setcode' => 'SOVR-EN015', 'quantity' => 1],
            ['setcode' => 'SOVR-EN017', 'quantity' => 1],
            ['setcode' => 'SOVR-EN018', 'quantity' => 1],
            ['setcode' => 'SOVR-EN019', 'quantity' => 1],
            ['setcode' => 'SOVR-EN020', 'quantity' => 1],
            ['setcode' => 'SOVR-EN022', 'quantity' => 2],
            ['setcode' => 'SOVR-EN023', 'quantity' => 1],
            ['setcode' => 'SOVR-EN027', 'quantity' => 2],
            ['setcode' => 'SOVR-EN031', 'quantity' => 2],
            ['setcode' => 'SOVR-EN032', 'quantity' => 1],
            ['setcode' => 'SOVR-EN033', 'quantity' => 1],
            ['setcode' => 'SOVR-EN054', 'quantity' => 2],
            ['setcode' => 'SOVR-EN091', 'quantity' => 1],
            ['setcode' => 'STBL-EN005', 'quantity' => 1],
            ['setcode' => 'STBL-EN014', 'quantity' => 1],
            ['setcode' => 'STBL-EN017', 'quantity' => 1],
            ['setcode' => 'STBL-EN055', 'quantity' => 1],
            ['setcode' => 'STBL-EN058', 'quantity' => 1],
            ['setcode' => 'STBL-EN090', 'quantity' => 1],
            ['setcode' => 'SYE-001', 'quantity' => 1],
            ['setcode' => 'SYE-002', 'quantity' => 1],
            ['setcode' => 'SYE-003', 'quantity' => 1],
            ['setcode' => 'SYE-006', 'quantity' => 1],
            ['setcode' => 'SYE-008', 'quantity' => 1],
            ['setcode' => 'SYE-010', 'quantity' => 1],
            ['setcode' => 'SYE-012', 'quantity' => 1],
            ['setcode' => 'SYE-013', 'quantity' => 1],
            ['setcode' => 'SYE-018', 'quantity' => 1],
            ['setcode' => 'SYE-019', 'quantity' => 1],
            ['setcode' => 'SYE-022', 'quantity' => 1],
            ['setcode' => 'SYE-037', 'quantity' => 1],
            ['setcode' => 'SYE-042', 'quantity' => 1],
            ['setcode' => 'SYE-016', 'quantity' => 1],
            ['setcode' => 'TAEV-EN008', 'quantity' => 1],
            ['setcode' => 'TAEV-EN009', 'quantity' => 1],
            ['setcode' => 'TAEV-EN018', 'quantity' => 1],
            ['setcode' => 'TAEV-EN020', 'quantity' => 1],
            ['setcode' => 'TAEV-EN022', 'quantity' => 1],
            ['setcode' => 'TAEV-EN023', 'quantity' => 1],
            ['setcode' => 'TAEV-EN024', 'quantity' => 1],
            ['setcode' => 'TAEV-EN025', 'quantity' => 1],
            ['setcode' => 'TAEV-EN027', 'quantity' => 1],
            ['setcode' => 'TAEV-EN030', 'quantity' => 1],
            ['setcode' => 'TAEV-EN057', 'quantity' => 1],
            ['setcode' => 'TAEV-EN075', 'quantity' => 1],
            ['setcode' => 'TDGS-EN001', 'quantity' => 3],
            ['setcode' => 'TDGS-EN003', 'quantity' => 2],
            ['setcode' => 'TDGS-EN004', 'quantity' => 3],
            ['setcode' => 'TDGS-EN005', 'quantity' => 1],
            ['setcode' => 'TDGS-EN006', 'quantity' => 3],
            ['setcode' => 'TDGS-EN007', 'quantity' => 1],
            ['setcode' => 'TDGS-EN008', 'quantity' => 2],
            ['setcode' => 'TDGS-EN011', 'quantity' => 2],
            ['setcode' => 'TDGS-EN012', 'quantity' => 1],
            ['setcode' => 'TDGS-EN015', 'quantity' => 1],
            ['setcode' => 'TDGS-EN017', 'quantity' => 3],
            ['setcode' => 'TDGS-EN018', 'quantity' => 1],
            ['setcode' => 'TDGS-EN021', 'quantity' => 1],
            ['setcode' => 'TDGS-EN022', 'quantity' => 1],
            ['setcode' => 'TDGS-EN024', 'quantity' => 3],
            ['setcode' => 'TDGS-EN026', 'quantity' => 1],
            ['setcode' => 'TDGS-EN027', 'quantity' => 2],
            ['setcode' => 'TDGS-EN028', 'quantity' => 2],
            ['setcode' => 'TDGS-EN031', 'quantity' => 2],
            ['setcode' => 'TDGS-EN032', 'quantity' => 2],
            ['setcode' => 'TDGS-EN036', 'quantity' => 2],
            ['setcode' => 'TDGS-EN037', 'quantity' => 1],
            ['setcode' => 'TDGS-EN038', 'quantity' => 1],
            ['setcode' => 'TDGS-EN048', 'quantity' => 2],
            ['setcode' => 'TDGS-EN049', 'quantity' => 3],
            ['setcode' => 'TDGS-EN058', 'quantity' => 1],
            ['setcode' => 'TDGS-EN059', 'quantity' => 1],
            ['setcode' => 'TDGS-EN062', 'quantity' => 1],
            ['setcode' => 'TDGS-EN073', 'quantity' => 1],
            ['setcode' => 'TDGS-EN084', 'quantity' => 1],
            ['setcode' => 'TDGS-EN087', 'quantity' => 1],
            ['setcode' => 'TDGS-EN096', 'quantity' => 1],
            ['setcode' => 'TLM-EN041', 'quantity' => 1],
            ['setcode' => 'TU01-EN016', 'quantity' => 1],
            ['setcode' => 'TU01-EN020', 'quantity' => 1],
            ['setcode' => 'YS11-EN001', 'quantity' => 1],
            ['setcode' => 'YS11-EN002', 'quantity' => 1],
            ['setcode' => 'YS11-EN003', 'quantity' => 1],
            ['setcode' => 'YS11-EN004', 'quantity' => 1],
            ['setcode' => 'YS11-EN005', 'quantity' => 1],
            ['setcode' => 'YS11-EN006', 'quantity' => 1],
            ['setcode' => 'YS11-EN007', 'quantity' => 1],
            ['setcode' => 'YS11-EN008', 'quantity' => 1],
            ['setcode' => 'YS11-EN009', 'quantity' => 1],
            ['setcode' => 'YS11-EN010', 'quantity' => 1],
            ['setcode' => 'YS11-EN011', 'quantity' => 1],
            ['setcode' => 'YS11-EN012', 'quantity' => 1],
            ['setcode' => 'YS11-EN013', 'quantity' => 1],
            ['setcode' => 'YS11-EN014', 'quantity' => 1],
            ['setcode' => 'YS11-EN015', 'quantity' => 1],
            ['setcode' => 'YS11-EN016', 'quantity' => 1],
            ['setcode' => 'YS11-EN017', 'quantity' => 1],
            ['setcode' => 'YS11-EN018', 'quantity' => 1],
            ['setcode' => 'YS11-EN019', 'quantity' => 1],
            ['setcode' => 'YS11-EN020', 'quantity' => 1],
            ['setcode' => 'YS11-EN021', 'quantity' => 1],
            ['setcode' => 'YS11-EN024', 'quantity' => 1],
            ['setcode' => 'YS11-EN027', 'quantity' => 1],
            ['setcode' => 'YS11-EN030', 'quantity' => 1],
            ['setcode' => 'YS11-EN034', 'quantity' => 1],
            ['setcode' => 'YS11-EN041', 'quantity' => 1],
            ['setcode' => 'YS11-EN043', 'quantity' => 1],
            ['setcode' => 'YSD-EN004', 'quantity' => 1],
        ];

        $aggregated = [];
        foreach ($rawCards as $card) {
            $key = mb_strtoupper(mb_trim($card['setcode']));
            if (isset($aggregated[$key])) {
                $aggregated[$key]['quantity'] += (int) $card['quantity'];
            } else {
                $aggregated[$key] = [
                    'setcode' => $key,
                    'quantity' => (int) $card['quantity'],
                ];
            }
        }

        $now = now();
        foreach ($aggregated as $card) {
            DB::table('yugioh_cards')->insert([
                'id' => (string) Str::uuid(),
                'setcode' => $card['setcode'],
                'quantity' => $card['quantity'],
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('yugioh_cards');
    }
};
