<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('independencia_cards', function (Blueprint $table): void {
            $table->string('id', 36)->primary();
            $table->string('deck', 10);
            $table->string('card_id', 10);
            $table->string('name');
            $table->string('type');
            $table->unsignedInteger('stars')->default(0);
            $table->string('monster_type')->nullable();
            $table->string('new_monster_type')->nullable();
            $table->unsignedInteger('attack')->default(0);
            $table->unsignedInteger('defense')->default(0);
            $table->text('description')->nullable();
            $table->text('effect')->nullable();
            $table->timestamps();
            $table->softDeletes();
            $table->userstampsUuid();
            $table->userstampsUuidSoftDeletes();

            $table->index(['deck', 'card_id'], 'independencia_cards_deck_card_id_index');
        });

        $cards = [
            [
                'deck' => '1',
                'card_id' => '1',
                'name' => 'El Bolívar de Plata',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'El 31 de marzo de 1879, bajo la segunda presidencia de Antonio Guzmán Blanco, se promulgó la Ley de monedas que estableció como unidad monetaria el Bolívar de Plata.',
                'effect' => 'Esta carta incrementa 500 puntos tanto sus puntos de ATQ y DEF como los de su oponente. Para lograr este efecto, ambos jugadores deben sacrificar dos cartas de su mano. Usted también puede aumentar sus puntos de vida sacrificando una carta efecto para así sumar los puntos de ATQ de dicha carta a sus puntos de vida.',
            ],
            [
                'deck' => '1',
                'card_id' => '2',
                'name' => 'Antonio José de Sucre',
                'type' => 'fire',
                'stars' => 7,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 3500,
                'defense' => 3500,
                'description' => '(Cumaná 03/02/1795 - 04/06/1830). Es considerado el militar más completo y cabal de los próceres de la Independencia. El 9 de diciembre de 1824 venció en la Batalla de Ayacucho a las tropas realistas al mando del virrey La Serna, y así liberó a América del Sur. Por esto se le confirió el titulo de Gran Mariscal.',
                'effect' => 'Ambos jugadores deben regresar las cartas del campo a sus respectivos mazos y luego barajarlos. Esta carta sólo puede ser destruida por la carta del Atentado Mortal.',
            ],
            [
                'deck' => '1',
                'card_id' => '3',
                'name' => 'Liberación de los Esclavos',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => '1 de junio de 1816. Simón Bolívar decreta en Carúpano la libertad de los esclavos para que así, se incorporen a las filas patrióticas.',
                'effect' => 'Esta carta permite recuperar una carta del Cementerio y aumenta 500 puntos de vida.',
            ],
            [
                'deck' => '1',
                'card_id' => '4',
                'name' => 'Cristobal Colón El Navegante',
                'type' => 'water',
                'stars' => 7,
                'monster_type' => 'Navegante',
                'new_monster_type' => 'hero',
                'attack' => 2500,
                'defense' => 2500,
                'description' => 'Famoso navegante de origen genovés. Al servicio de los Reyes Católicos se embarca en un gran viaje en el que descubre el continente Americano en 1492.',
                'effect' => 'Al activar esta carta, coloque el mazo de su oponente boca arriba y lance una moneda. Si cae cara usted puede destruir la carta que desee; si cae sello su oponente debe destruir una carta que esté boca abajo en el campo.',
            ],
            [
                'deck' => '1',
                'card_id' => '6',
                'name' => 'Batalla de Carabobo',
                'type' => 'fire',
                'stars' => 10,
                'monster_type' => 'Batalla',
                'new_monster_type' => 'event',
                'attack' => 6500,
                'defense' => 6500,
                'description' => '24 de junio de 1821. En esta batalla el ejército patriota logra la liberación del territorio venezolano.',
                'effect' => 'Esta carta sólo puede ser invocada al fusionar la carta de Bolívar con la de Páez. Además, para invocar este gran poder, debe sacrificar o haber utilizado durante el duelo tres cartas indio. Esta carta no puede ser destruida por ninguna carta trampa o mágica.',
            ],
            [
                'deck' => '1',
                'card_id' => '7',
                'name' => 'Antonio Ricaurte',
                'type' => 'fire',
                'stars' => 7,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 2000,
                'defense' => 3000,
                'description' => '(Villa de Leiva, Colombia 10/07/1786 - San Mateo, Estado Aragua 25/03/1814). Capitán que luchó por la libertad de Venezuela en la Guerra de la Independencia. Se sacrificó prendiéndole fuego al polvorin para evitar que la pólvora cayera en manos de Boves, y así asegurar el triunfo de los patriotas.',
                'effect' => 'Destruye las cartas trampa y mágicas de su oponente que estén en el campo',
            ],
            [
                'deck' => '1',
                'card_id' => '9',
                'name' => 'El Terremoto de 1812',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'A las 4:07 de la tarde del día 26 de marzo se produce en Caracas, un terremoto que ocasionó grandes daños y la muerte de cerca de 12000 personas. Fue entonces cuand Bolívar pronunció su famosa frase: "Aunque la naturaleza se oponga lucharemos contra ella y haremos que nos obedezca". ',
                'effect' => 'Destruya todas las cartas del campo, tanto las suyas como las de su oponente. Luego lance una moneda, si es cara inflija un daño de 500 puntos de vida a su oponente.',
            ],
            [
                'deck' => '1',
                'card_id' => '13',
                'name' => 'Fortalezas',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Las fortificaciones a lo largo de las Costas Venezolanas, fueron cradas para protegerse de los constantes ataques de los piratas dél Caribe.',
                'effect' => 'Esta carta aumenta 500 puntos la DEF de todas tus cartas. Lance una moneda. Si cae cara, aumenta sus puntos de vida, 500 puntos por cada carta efecto que exista en el campo de batalla; si cae sello, aplique el efecto a su oponente.',
            ],
            [
                'deck' => '1',
                'card_id' => '16',
                'name' => 'Rafael Urdaneta',
                'type' => 'light',
                'stars' => 8,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 2000,
                'defense' => 2000,
                'description' => 'General del ejército republicano. Nació en Maracaibo en 1789. Se destacó por su don de mando en casi todas las campañas de la Guerra de Independencia. Murió en Paris en 1845.',
                'effect' => 'Sacrifique esta carta para devolver a su mazo una carta que haya sido enviada al Cementerio que tenga igual o menor número de estrellas.',
            ],
            [
                'deck' => '1',
                'card_id' => '17',
                'name' => 'José Gregorio Monagas',
                'type' => 'light',
                'stars' => 4,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 1500,
                'defense' => 1500,
                'description' => '(1796 - 1858) General del ejército republicano natural de Aragua de Barcelona. Se le conoció con el sobrenombre de Primera Lanza de Oriente, como lo bautizó Bolívar. Fue presidente de Venezuela de 1851 hasta 1855. Murió en Maracaibo.',
                'effect' => '',
            ],
            [
                'deck' => '1',
                'card_id' => '18',
                'name' => 'Campaña Admirable',
                'type' => 'fire',
                'stars' => 8,
                'monster_type' => 'Batalla',
                'new_monster_type' => 'event',
                'attack' => 3500,
                'defense' => 3500,
                'description' => 'Bolívar realizó esta campaña en seis meses y con la misma se propuso liberar a Venezuela del poder español. La emprendió desde Cúcuta y ocupó Caracas triunfante. El 7 de Agosto de 1813, se hizo acreedor del título de El Libertador.',
                'effect' => 'Lance el dado y recupere del Cementerio tantas cartas como números sea el resultado. Vuelva a lanzar el dado y envíe el mismo número de cartas de su oponente al Cementerio.',
            ],
            [
                'deck' => '1',
                'card_id' => '19',
                'name' => 'Ezequiel Zamora',
                'type' => 'fire',
                'stars' => 6,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 1500,
                'defense' => 1500,
                'description' => 'Nació en Cúa, Estado Miranda en 1817. Fue desterrado a Curazao por el general Cipriano Castro. Regresa en 1859 para iniciar la Guerra Federal. Murió en combate en San Carlos de Cojedes en 1860.',
                'effect' => 'Recupere 1000 puntos de vida al sacrificar esta carta.',
            ],
            [
                'deck' => '1',
                'card_id' => '20',
                'name' => 'La Libertadora del Libertador',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Manuela Sáenz (Quito 1797 - Perú 1856). Compañera del Libertador y patriota ecuatoriana. Fue llamada Libertadora por salvarle la vida a Bolívar la noche del 25 de Septiembre de 1828.',
                'effect' => 'Ningún ataque puede ser realizado durante el mismo turno en el que haya sido invocada esta carta. Sólo puede ser utilizada una vez.',
            ],
            [
                'deck' => '1',
                'card_id' => '21',
                'name' => 'José Antonio Páez',
                'type' => 'fire',
                'stars' => 6,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 2000,
                'defense' => 2000,
                'description' => '(Curpa, Estado Portuguesa 13/06/1790 - Nueva York 06/03/1873) General en jefe de la Independencia y presidente de la República en tres oportunidades.',
                'effect' => 'Esta carta es un poco peligrosa, ya que puede atacar bien sea a los puntos de vida de su oponente como los suyos. Para activar el efecto de esta carta debe lanzar una moneda. Si cae cara, inflige un daño directo a la vida de su oponente; si cae sello, el daño le es infligido a usted.',
            ],
            [
                'deck' => '1',
                'card_id' => '22',
                'name' => 'Santiago Mariño',
                'type' => 'water',
                'stars' => 7,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 2000,
                'defense' => 2000,
                'description' => 'Nació en la Isla de Margarita en 1788. Llegó a ser general, grado que le fue conferido por El Libertador. Fue candidato a la presidencia de la República en 1850. Murió en la Victoria en 1854.',
                'effect' => 'Suprime el efecto de todas las cartas trampa que se encuentren en el campo durante el turno en el que esta carta está activada.',
            ],
            [
                'deck' => '1',
                'card_id' => '23',
                'name' => 'Firma del Acta de la Independencia',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'El Acta de la Independencia se firmó el día 19 de Abril de 1810 y fue redactada por los diputados Juan Germán Roscio y Francisco Isnardy.',
                'effect' => 'Seleccione y controle una carta de su oponente sin importar su posición en el campo hasta el final del turno.',
            ],
            [
                'deck' => '1',
                'card_id' => '24',
                'name' => 'Manuel Piar',
                'type' => 'agua',
                'stars' => 6,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 1500,
                'defense' => 1500,
                'description' => 'Nació en Bonaire en 1782. Se incorporó a las filas del ejército republicano a raíz de los acontecimientos de 1810. Obtuvo victorias militares en el Juncal y San Félix y ocupó las misiones de Caroní, las que eran de suma importancia para los patriotas. Murió fusilado en 1817.',
                'effect' => 'Esta carta le permite sumar los puntos de ATQ y DEF para utilizarlos como puntos de ATQ pero sin DEF y viceversa.',
            ],
            [
                'deck' => '1',
                'card_id' => '25',
                'name' => 'Cacique Tamanaco',
                'type' => 'water',
                'stars' => 4,
                'monster_type' => 'Indio / Guerrero',
                'new_monster_type' => 'warrior',
                'attack' => 1000,
                'defense' => 2000,
                'description' => 'Cacique de los Indios Mariches que colaboró con Guacaipuro en la defensa del Valle de Caracas. Principal dirigente de la resistencia indígena contra distintos invasores que atraídos por la belleza y riqueza del valle pretendieron conquistarlo.',
                'effect' => '',
            ],
            [
                'deck' => '1',
                'card_id' => '26',
                'name' => 'Negro Primero',
                'type' => 'earth',
                'stars' => 6,
                'monster_type' => 'Soldado',
                'new_monster_type' => 'warrior',
                'attack' => 1500,
                'defense' => 2500,
                'description' => 'El célebre llanero cuyo nombre verdadero era Pedro Camejo sirvió a los realistas al mando de Boves. En 1816 se incorpora al ejército republicano a las órdenes de Paéz. Múrio heroicamente en la Batalla de Carabobo',
                'effect' => '',
            ],
            [
                'deck' => '1',
                'card_id' => '27',
                'name' => 'Antonio Anzoátegui',
                'type' => 'fire',
                'stars' => 7,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 2000,
                'defense' => 2000,
                'description' => 'Nació en Barcelona en 1793. Fue compañero inseparable de Bolívar y se distinguió por su valentía en los combates de Mosquitero, Carabobo, San Mateo, Anaure y La Puerta. Murió en Pamplona en 1819.',
                'effect' => '',
            ],
            [
                'deck' => '1',
                'card_id' => '28',
                'name' => 'José Tadeo Monagas',
                'type' => 'earth',
                'stars' => 7,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 2850,
                'defense' => 2850,
                'description' => 'Nació en 1784. Fue general del ejército republicano y se distinguió por su poder de mando al frente de sus aguerridos lanceros. Se retiró de la vida militar en 1822. Fue presidente de la república y gobernó arbitrariamente. Por esta razón, fue derrocado por Julián Castro. Murió en Caracas en 1868.',
                'effect' => '',
            ],
            [
                'deck' => '1',
                'card_id' => '29',
                'name' => 'Juan Bautista Arismendi',
                'type' => 'earth',
                'stars' => 6,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 2600,
                'defense' => 2600,
                'description' => '(1775 - 1841) General del ejército republicano. Participó activamente en la causa independentista y fue nombrado vicepresidente de la república por el Congreso de Angostura en 1819.',
                'effect' => '',
            ],
            [
                'deck' => '1',
                'card_id' => '30',
                'name' => "Daniel Florencio O'Leary",
                'type' => 'water',
                'stars' => 6,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 2400,
                'defense' => 2400,
                'description' => 'Nació en Irlanda en 1802. Se destacó por su valentía en el ejército republicano y además, fue edecán del Libertador. Murió en Bogotá en 1854.',
                'effect' => '',
            ],
            [
                'deck' => '1',
                'card_id' => '31',
                'name' => 'Teresa Carreño',
                'type' => 'trap',
                'stars' => 0,
                'monster_type' => 'trap',
                'new_monster_type' => 'trap',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Excelente pianista, nació en Caracas en 1853. Triunfó en Estados Unidos, América Latina y Europa, especialmente en Alemania donde se residenció. Murió en Nueva York en 1917.',
                'effect' => 'Elimine el efecto de la carta que lo ataque y sume a sus puntos de vida los puntos de ATQ de dicha carta.',
            ],
            [
                'deck' => '1',
                'card_id' => '32',
                'name' => 'José Francisco Bermúdez',
                'type' => 'water',
                'stars' => 5,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 2500,
                'defense' => 2500,
                'description' => 'Nació en Cariaco en 1782 y murió asesinado en Cumaná en 1831. General y prócer de la Independencia, participó junto a Páez en la toma del Castillo de Puerto Cabello en 1823, última posición militar española en Venezuela.',
                'effect' => '',
            ],
            [
                'deck' => '1',
                'card_id' => '33',
                'name' => 'Jóse Félix Ribas',
                'type' => 'earth',
                'stars' => 8,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 2500,
                'defense' => 2400,
                'description' => '(Caracas 19/09/1775 - Tucupido, Estado Guárico 31/01/1815). Oficial general en jefe durante la Guerra de Independencia. Comenzó su actividad republicana en 1810. Participó en numerosas batallas, pero una de la más importantes fue la de la Victoria en 1814.',
                'effect' => 'Fusione esta carta con la de Batalla de la Victoria para eliminar la carta de Boves El Temible.',
            ],
            [
                'deck' => '1',
                'card_id' => '34',
                'name' => 'Los Símbolos Patrios',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'LA BANDERA: El Generalisimo Francisco de Miranda trajo la bandera en el año de 1806. EL ESCUDO: Representa la historia de Venezuela. EL HIMNO NACIONAL: Lo escribió el prócer Vicente Salias y la música es de Juan José Landaeta.',
                'effect' => 'Esta carta le permite realizar cualquiera de las siguientes jugadas:
1) Aumentar 500 puntos de vida;
2) Puede invocar esta carta para fusionar dos cartas con un ATQ menor de 1600;
3) Puede recuperar a un prócer que se encuentre en el Cementerio.',
            ],
            [
                'deck' => '1',
                'card_id' => '35',
                'name' => 'José María España',
                'type' => 'fire',
                'stars' => 7,
                'monster_type' => 'Soldado',
                'new_monster_type' => 'warrior',
                'attack' => 1500,
                'defense' => 1500,
                'description' => 'Patriota nacio en La Guaira en 1760. Conjuntamente con Manuel Gual se dédicó a conspirar en favor de la independencia. Al ser descubierto el plan, tuvo que huir del país. Asu regreso fue encarcelado y ejecutado en 1799.',
                'effect' => '',
            ],
            [
                'deck' => '1',
                'card_id' => '36',
                'name' => 'Vuelvan Caras',
                'type' => 'trap',
                'stars' => 0,
                'monster_type' => 'trap',
                'new_monster_type' => 'trap',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Maniobra ejecutada por Páez en la batalla de Las Queseras en 1819 que consistió en cambiar la dirección de la retaguardia. Entonces al emprender la retirada los patriotas vuelven caras a sus perseguidores.',
                'effect' => 'Sacrifique esta carta y recuperela del cementerio en cualquier momento del juego para aumentar 1000 puntos su vida y disminuir 1000 puntos la de su oponente.',
            ],
            [
                'deck' => '1',
                'card_id' => '37',
                'name' => 'Cristóbal Mendoza',
                'type' => 'light',
                'stars' => 5,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 1500,
                'defense' => 1500,
                'description' => 'Nació en Trujillo en 1772. Como abogado se desempeño en el cargo de protector de los indios en la Administración Colonial, además de ejercer diversos cargos en la Administración de Justicia.',
                'effect' => '',
            ],
            [
                'deck' => '1',
                'card_id' => '38',
                'name' => 'Batalla de Boyacá',
                'type' => 'fire',
                'stars' => 7,
                'monster_type' => 'Batalla',
                'new_monster_type' => 'event',
                'attack' => 3000,
                'defense' => 3000,
                'description' => 'Batalla librada el 6 de Agosto de 1819. Fue decisiva en las guerras de emancipación de Ameérica. Se llevó a cabo en la zona de Boyacá (Nueva Granada).',
                'effect' => 'Reduce el ATQ de su oponente a cero. Este efecto sólo puede ser usado una sola vez en el juego.',
            ],
            [
                'deck' => '1',
                'card_id' => '39',
                'name' => 'Batalla de Victoria',
                'type' => 'fire',
                'stars' => 8,
                'monster_type' => 'Batalla',
                'new_monster_type' => 'event',
                'attack' => 3200,
                'defense' => 3200,
                'description' => 'El 12 de febrero de 1814 José Félix Ribas y Campos Elías, conjuntamente con un grupo de jóvenes universitarios libraron esta gloriosa batalla, en la que Boves fue derrotado. Por esto, en esta fecha se celebra el Día de la Juventud en nuestro país.',
                'effect' => 'Fusione esta carta con la de José Félix Ribas y destruya la carta de Boves El Temible.',
            ],
            [
                'deck' => '1',
                'card_id' => '40',
                'name' => 'La Batalla del Juncal',
                'type' => 'water',
                'stars' => 5,
                'monster_type' => 'Batalla',
                'new_monster_type' => 'event',
                'attack' => 1500,
                'defense' => 1500,
                'description' => 'Histórica batalla que se llevó a cabo el 27-09-1816 en en las cercanías de Barcelona en la que los patriotas al mando de Piar derrotaron a Morales.',
                'effect' => 'Esta carta le permite tomar dos cartas más del mazo y jugar con 7 cartas en su mano sólo durante dos turnos.',
            ],
            [
                'deck' => '1',
                'card_id' => '41',
                'name' => 'El Cacique Terepaima',
                'type' => 'fire',
                'stars' => 6,
                'monster_type' => 'Indio / Guerrero',
                'new_monster_type' => 'warrior',
                'attack' => 2500,
                'defense' => 2500,
                'description' => 'Derrotó a Luis de Narváez durante la expedición que realizó en auxilio de Francisco Fajardo. Venció a Diego de Losada el 25/07/2567 en la jornada que culminaría con la fundación de Caracas. Sólo Garci González de Silva pudo vencerlo.',
                'effect' => '',
            ],
            [
                'deck' => '1',
                'card_id' => '42',
                'name' => 'Batalla Naval del Lago de Maracaibo',
                'type' => 'water',
                'stars' => 9,
                'monster_type' => 'Batalla',
                'new_monster_type' => 'event',
                'attack' => 3000,
                'defense' => 3000,
                'description' => '(24-07-1823) Última batalla decisiva en las campañas navales de la independencia. Dos horas de recio combate abrieron el camino para las negociaciones en las que los españoles se comprometieron a entregar todos los territorios ocupados.',
                'effect' => 'Al azar, elija una carta de su oponente en modo de ATQ y cámbiela a modo de DEF, y atáquelo con esta carta.',
            ],
            [
                'deck' => '1',
                'card_id' => '43',
                'name' => 'Batalla de San Félix',
                'type' => 'fire',
                'stars' => 5,
                'monster_type' => 'Batalla',
                'new_monster_type' => 'event',
                'attack' => 1200,
                'defense' => 1200,
                'description' => 'El general Piar logra la victoria frente al realista La Torre. Con esta batalla los patriotas recuperaron el Territorio de Guayana y el Camino del Oriente.',
                'effect' => 'Elimine todas las cartas mágicas del campo de su oponente y si no hay niguna carta trampa activada, ataque los puntos de vida de su oponente.',
            ],
            [
                'deck' => '1',
                'card_id' => '44',
                'name' => 'José Cortés de Madariaga',
                'type' => 'trap',
                'stars' => 0,
                'monster_type' => 'trap',
                'new_monster_type' => 'trap',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Sacerdote y héroe de la Independencia. Nació en Chile en 1770. Su valiente y dedicada actuación el 19 de abril de 1826 cuando exhortó al pueblo a rechazar a Emparan le ha merecido un lugar de honor en nuestra historia.',
                'effect' => 'Lance un dado y multiplique por 200 el número obtenido. Luego, sume esta cantidad a sus puntos de vida.',
            ],
            [
                'deck' => '1',
                'card_id' => '45',
                'name' => 'Declaración de la Independencia',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Se aprobó el 5 de Julio de 1811, estando representadas las provincias de Caracas, Cumana, Barinas, Margarita, Barcelona, Mérida y Trujillo. Este hecho marcó la fundación del Estado Venezolano. ',
                'effect' => 'Seleccione una carta bien sea de su oponente o de su propio cementerio y colóquela boca arriba bajo su control en posición de ATQ o DEF.',
            ],
            [
                'deck' => '1',
                'card_id' => '46',
                'name' => 'Decreto de Guerra a Muerte',
                'type' => 'trap',
                'stars' => 0,
                'monster_type' => 'trap',
                'new_monster_type' => 'trap',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Proclamado por Bolívar el 15-06-1813, debido a la ferocidad de la lucha y al irrespeto de los realistas por las leyes.',
                'effect' => 'Puede activar esta carta cuando sea atacado. Al sacrificar esta carta el ATQ y DEF de su oponente se reduce a la mitad',
            ],
            [
                'deck' => '1',
                'card_id' => '48',
                'name' => 'Congreso de Angostura',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Se reunió el 15 de febrero de 1819. Allí, Bolívar expuso los principios más adecuados para la organización de la República, entre los que mencionó la democracia, soberanía del pueblo y la división de poderes. Introdujo también el poder moral en lo que él llamó Código de Leyes.',
                'effect' => 'Esta carta le permite fusionar dos cartas de manera especial y sumar sus puntos de ATQ y DEF.',
            ],
            [
                'deck' => '1',
                'card_id' => '49',
                'name' => 'Creación de la Gran Colombia',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Fue el gran sueño de Bolívar. Duró once años, desde 1819 hasta 1830 y estuvo conformada por Venezuela, Quito y Cundinamarca. Se disolvió a causa de intereses personales y rivalidades.',
                'effect' => 'Esta carta le permite bloquear el ATQ de su oponente por un turno si no esta activada la carta de Páez.',
            ],
            [
                'deck' => '1',
                'card_id' => '50',
                'name' => 'El Cacique Gayaurima',
                'type' => 'fire',
                'stars' => 5,
                'monster_type' => 'Indio / Guerrero',
                'new_monster_type' => 'warrior',
                'attack' => 1500,
                'defense' => 3000,
                'description' => 'Cacique de los indios Cumanagotos. Organizó y dirgió la resistencia de los indios contra los conquistadores españoles en la región Oriental.',
                'effect' => '',
            ],
            [
                'deck' => '2',
                'card_id' => '1',
                'name' => 'Miranda en la Carraca',
                'type' => 'trap',
                'stars' => 0,
                'monster_type' => 'trap',
                'new_monster_type' => 'trap',
                'attack' => 0,
                'defense' => 0,
                'description' => 'El Generalísimo Francisco de Miranda es conducido a la Fortaleza de la Carraca (Cádiz) por considerar los patriotas que la capitulación ante Monteverde había sido una traición a la Patria.',
                'effect' => 'Active esta carta cuando su oponente lo ataque con la carta de Francisco Miranda. El efecto de esta carta es eliminado y devuelto a su oponente, pero duplicado (1600 puntos de vida de daño directo)',
            ],
            [
                'deck' => '2',
                'card_id' => '2',
                'name' => 'El Terremoto de 1812',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'A las 4:07 de la tarde del día 26 de marzo se produce en Caracas, un terremoto que ocasionó grandes daños y la muerte de cerca de 12000 personas. Fue entonces cuand Bolívar pronunció su famosa frase: "Aunque la naturaleza se oponga lucharemos contra ella y haremos que nos obedezca". ',
                'effect' => 'Destruya todas las cartas del campo, tanto las suyas como las de su oponente. Luego lance una moneda, si es cara inflija un daño de 500 puntos de vida a su oponente.',
            ],
            [
                'deck' => '2',
                'card_id' => '3',
                'name' => 'El Pirata Nicolás Valier',
                'type' => 'water',
                'stars' => 6,
                'monster_type' => 'Pirata / Nefasto',
                'new_monster_type' => 'pirate',
                'attack' => 2400,
                'defense' => 2400,
                'description' => 'Pirata francés que incendió y saqueó la ciudad de Coro en 1567.',
                'effect' => 'Su oponente debe enviar todas las cartas que se encuentran en su campo al final del mazo. Esto le inflingirá un daño directo de 800 puntos de vida.',
            ],
            [
                'deck' => '2',
                'card_id' => '3',
                'name' => 'El Descubrimiento',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Famoso navegante de origen genovés. Al servicio de los Reyes Católicos se embarca en un gran viaje en el que descubre el continente Americano en 1492.',
                'effect' => 'Al activar esta carta, coloque el mazo de su oponente boca arriba y descubra las cartas de su mano. Luego, lance una moneda. Si es cara, destruya la carta que desee; si es sello, su oponente debe destruir una carta del campo al azar.',
            ],
            [
                'deck' => '2',
                'card_id' => '4',
                'name' => 'Francisco Morales',
                'type' => 'dark',
                'stars' => 7,
                'monster_type' => 'Comandante / Realista',
                'new_monster_type' => 'commander',
                'attack' => 2300,
                'defense' => 2000,
                'description' => 'Un guerrero de infinita cureldad. Asesinó a prisioneros, y un gran número de personas, sin respetar edad ni sexo, en el recinto de una iglesia.',
                'effect' => 'Elimina cinco cartas del Cementerio de tu oponente, escoge dos y colócalas en tu mano.',
            ],
            [
                'deck' => '2',
                'card_id' => '5',
                'name' => 'Andrés Bello un Gran Maestro',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => '(Caracas 29/11/1781 - Santiago de Chile 16/10/1865). Humanista, poeta, legislador, filósofo, educador, crítico y filólogo.',
                'effect' => 'Aumenta 500 puntos de ATQ y DEF a todos los próceres y 1000 puntos de ATQ a la carta de Simón Bolívar si está en el campo en posición de ATQ.',
            ],
            [
                'deck' => '2',
                'card_id' => '6',
                'name' => 'Boves El Temible',
                'type' => 'fire',
                'stars' => 10,
                'monster_type' => 'Comandante / Realista',
                'new_monster_type' => 'commander',
                'attack' => 4750,
                'defense' => 4750,
                'description' => 'Nació en 1782 en Asturias. Se caracterizó por ser un gran enemigo de la causa republicana y por su odio a los patriotas. Cayó abatido por una lanza patriota en Urica en 1814.',
                'effect' => 'Si esta carta es atacada por una carta de menor poder, los puntos de ATQ y DEF de esta última se le suman a la primera, lo que incrementa su poder durante todos los turnos. Esta carta sólo puede ser eliminada al invocar una fusión.',
            ],
            [
                'deck' => '2',
                'card_id' => '6',
                'name' => 'Simón Bolívar El Libertador',
                'type' => 'light',
                'stars' => 11,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 4500,
                'defense' => 4500,
                'description' => '(Caracas 24/07/1783 - Santa Marta, Colombia 17/12/1830). Libertador de Venezuela, Colombia, Ecuador, Perú, Bolivia y consecuentemente, Panamá. Obtuvo el titulo de Libertador el 14/10/1813.',
                'effect' => 'Este legendario guerrero posee una fuerza increible. Sólo puede ser eliminado por la carta Tuberculosis Infernal. Esta carta puede infligir daño directo a los puntos de vida de su oponente si no posee una carta de los realistas en el campo. Al fusionarse con Paéz activa la gran Batalla de Carabobo.',
            ],
            [
                'deck' => '2',
                'card_id' => '7',
                'name' => 'La Esclavitud',
                'type' => 'trap',
                'stars' => 0,
                'monster_type' => 'trap',
                'new_monster_type' => 'trap',
                'attack' => 0,
                'defense' => 0,
                'description' => 'La esclavitud de los aborígenes comenzó con el descubrimiento del nuevo continente. Ellos eran sometidos a durísimos trabajos al igual que los negros traídos de África.',
                'effect' => 'Invoque esta carta cuando sea atacado por una carta de INDIO GUERRERO y conviértalo en su esclavo aumentando su ATQ y DEF al doble.',
            ],
            [
                'deck' => '2',
                'card_id' => '8',
                'name' => 'Fortalezas',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Las fortificaciones a lo largo de las Costas Venezolanas, fueron cradas para protegerse de los constantes ataques de los piratas dél Caribe.',
                'effect' => 'Esta carta aumenta 500 puntos la DEF de todas tus cartas. Lance una moneda. Si cae cara, aumenta sus puntos de vida, 500 puntos por cada carta efecto que exista en el campo de batalla; si cae sello, aplique el efecto a su oponente.',
            ],
            [
                'deck' => '2',
                'card_id' => '9',
                'name' => 'Tuberculosis Infernal',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Bolívar llega a Santa Marta, Colombia el día 1 de Diciembre muy enfermó. Fue atendido por el médico francés Alejandro Próspero Reverend. Murió en la quita de San Pedro Alejandrino el 17 de diciembre de 1830.',
                'effect' => 'Es la única carta que destruye la carta del Libertador, envíandola al cementerio y eliminado todo sus efectos. También puede utilizar esta carta para infligir un daño directo de 1000 puntos de vida a su oponente.',
            ],
            [
                'deck' => '2',
                'card_id' => '10',
                'name' => 'El Atentado Mortal',
                'type' => 'trap',
                'stars' => 0,
                'monster_type' => 'trap',
                'new_monster_type' => 'trap',
                'attack' => 0,
                'defense' => 0,
                'description' => '4 de junio de 1830. El Mariscal Antonio José de Sucre es asesinado en Berruecos, Colombia.',
                'effect' => 'Esta carta con su poder verdaderamente catastrófico destruye la carta del Mariscal Sucre y la envía al cementerio. Mientras esta carta esté activada, su oponente no puede invocar ninguna Fusión Especial en el campo.',
            ],
            [
                'deck' => '2',
                'card_id' => '10',
                'name' => 'El Mito del Dorado',
                'type' => 'trap',
                'stars' => 0,
                'monster_type' => 'trap',
                'new_monster_type' => 'trap',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Los aborígenes le contaron a los españoles que existía una ciudad de oro que llamaron "El Dorado". Los españoles la buscaron por todas partes, desde el Atlántico hasta el altiplano de Bogotá, sin conseguirlo jamás.',
                'effect' => 'Utilice esta carta a la mitad del turno de su oponente, para así interrumpir su jugada. Luego, coloque tres cartas de su mano al final del mazo.',
            ],
            [
                'deck' => '2',
                'card_id' => '11',
                'name' => 'Pablo Morillo',
                'type' => 'fire',
                'stars' => 6,
                'monster_type' => 'General',
                'new_monster_type' => 'general',
                'attack' => 2500,
                'defense' => 2500,
                'description' => '(1778 - 1836) General del ejército español, designado por Fernando VII para reprimir la resistencia del ejército republicano en Nueva Granada. Puso en práctica una cruel política de represalia y ejecuciones de la que fue víctima gran parte de la población civil.',
                'effect' => '',
            ],
            [
                'deck' => '2',
                'card_id' => '11',
                'name' => 'El Cacique Guaicaipuro',
                'type' => 'earth',
                'stars' => 6,
                'monster_type' => 'Indio / Guerrero',
                'new_monster_type' => 'warrior',
                'attack' => 2500,
                'defense' => 2500,
                'description' => 'Reconocido por los caciques Naiguatá , Guaicamacuto, Chacao y Baruta como su Jefe Supremo, debido a que impulsó un levantamiento de todas sus tribus para luchar fieramente contra los españoles.',
                'effect' => '',
            ],
            [
                'deck' => '2',
                'card_id' => '12',
                'name' => 'La Compañía Guipuzcoana',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'La Compañía Guipuzcoana de Caracas fue fundada en 1728. Tenía el deber de abastecer la provincia de Caracas y de perseguir el contrabando. Se ordenó su disolución oficial el 10/03/1785.',
                'effect' => 'Mientras esta carta permanezca boca arriba en el campo, no hay límites en el número de cartas en las manos de ambos jugadores.',
            ],
            [
                'deck' => '2',
                'card_id' => '12',
                'name' => 'El Tirano Lopez Aguirre',
                'type' => 'fire',
                'stars' => 6,
                'monster_type' => 'Aventurero',
                'new_monster_type' => 'adventurer',
                'attack' => 2500,
                'defense' => 2500,
                'description' => '(1592 - 1651) Célebre aventurero español, conocido por el sobrenombre de El Tirano. Tomó el mando de una expedición que se dirigía a la conquista de El Dorado, asesinó a todos los jefes y se declaró en rebeldía frente al rey de España.',
                'effect' => '',
            ],
            [
                'deck' => '2',
                'card_id' => '13',
                'name' => 'José de Canterac',
                'type' => 'fire',
                'stars' => 5,
                'monster_type' => 'General',
                'new_monster_type' => 'general',
                'attack' => 2500,
                'defense' => 2500,
                'description' => 'General del ejército realista. Se enfrentó a Bolívar en la Batalla de Junín (Perú). El ejército de Canterac recibió un golpe mortal y huyó despavorido.',
                'effect' => '',
            ],
            [
                'deck' => '2',
                'card_id' => '14',
                'name' => 'La Ofrenda',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Indios Mesoamericanos
Indígenas venezolanos Arawacos, Caríbes y Timoto-cuicas. Primeros pobladores de Venezuela. Fueron hechos esclavos y torturados por los conquistadores.',
                'effect' => 'Al activar esta carta, su ATQ, DEF y vida aumenta 1000 puntos. El efecto de e4sta carta sólo puede ser eliminado al utilizar la carta de Liberación de los Esclavos.',
            ],
            [
                'deck' => '2',
                'card_id' => '14',
                'name' => 'Simón Rodríguez un Gran Maestro',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => '(Caracas 28/10/1771 - Amotape, Perú 23/02/1854). Educador y maestro del Libertador que influyó en sus ideas independentistas.',
                'effect' => 'Aumenta 500 puntos de ATQ y DEF a la carta del Libertador. Además, puede apelar a su sabiduría seleccionando una carta de su oponente y haciendo una reseña histórica de la misma. De esta manera, usted podrá controlar la carta y atacar los puntos de vida de su oponente.',
            ],
            [
                'deck' => '2',
                'card_id' => '15',
                'name' => 'Luisa Cáceres de Arismendi',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => '(1779 - 1866) Heroína de la Guerra de Independencia, esposa del prócer y general Juan Bautista Arismendi. Fue tomada prisionera por los realista en presesalía por la rebeldía de su marido. Pierde a su hija en la prisión.',
                'effect' => 'Al utilizar esta carta, la jugada que realizó su oponente durante su turno pierde su efecto. El efecto de esta carta sólo se activa si hace una breve historia de una carta de la mano de su oponente. Él escoge la carta.',
            ],
            [
                'deck' => '2',
                'card_id' => '15',
                'name' => 'Generalísimo Francisco de Miranda',
                'type' => 'light',
                'stars' => 7,
                'monster_type' => 'Prócer de la Independencia',
                'new_monster_type' => 'hero',
                'attack' => 3200,
                'defense' => 3200,
                'description' => '(Caracas 28/03/1750 - Cádiz, España 14/07/1816) Se le reconoce como el "Primer Criollo Universal". Participó en la independencia de Estados Unidos, La Revolución Francesa y en la lucha por la libertad de Hispanoamérica. Es el único latinoamericano inmortalizado en el Arco del Triunfo en Francia.',
                'effect' => 'Seleccione dos cartas de su mano y retírelas del juego para infligir 800 puntos de daño directo a la vida de su oponente.',
            ],
            [
                'deck' => '2',
                'card_id' => '16',
                'name' => 'Arzobispo Narciso Coll y Pratt',
                'type' => 'trap',
                'stars' => 0,
                'monster_type' => 'trap',
                'new_monster_type' => 'trap',
                'attack' => 0,
                'defense' => 0,
                'description' => '(1754 - 1822) Arzobispo español. Llegó a La Guaira con el propósito de defender a su Iglesia y a su rey. Por un lado, los realistas lo acusaban de mantener relaciones con los insurgentes, y por el otro, los patriotas le reprochaban su lealtad a Fernando VII.',
                'effect' => 'Sacrifique esta carta cuando sea atacado para reducir el ATQ y DEF de su oponente a la mitad.',
            ],
            [
                'deck' => '2',
                'card_id' => '17',
                'name' => 'Diego de Losada',
                'type' => 'fire',
                'stars' => 6,
                'monster_type' => 'Conquistador',
                'new_monster_type' => 'conqueror',
                'attack' => 2500,
                'defense' => 2500,
                'description' => 'Conquistador, Fundó la ciudad de Santiago de León de Caracas el 25 de julio de 1567. Las ordenes de los reyes de España trajero como consecuencia conquistas muy costosas, que además provocaron la muerte de muchos indígenas.',
                'effect' => '',
            ],
            [
                'deck' => '2',
                'card_id' => '18',
                'name' => 'Los Cañones',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'La pólvora fue utilizada primero por los conquistadores españoles para reprimir a los indios.',
                'effect' => 'Active esta carta si es atacado por los indios o por próceres cuyo ATQ sea 2500 puntos o menos y destruya a su oponente sin que nada pueda impedirlo.',
            ],
            [
                'deck' => '2',
                'card_id' => '19',
                'name' => 'Alonso de Ojeda',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => '(1466 - 1516) Alonso de Ojeda acompaña a Colón en el Segundo Viaje. Obtuvo permiso para realizar una expedición. Pasó por Margarita y entró al Golfo de Venezuela. Allí observó los palafitos que le sugirieron el nombre de Pequeña Venecia o Venezuela.',
                'effect' => 'Esta carta le permite explorar el mazo de su oponente sólo por un turno.',
            ],
            [
                'deck' => '2',
                'card_id' => '20',
                'name' => 'La Compañía Guipuzcoana',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'La Compañía Guipuzcoana de Caracas fue fundada en 1728. Tenía el deber de abastecer la provincia de Caracas y de perseguir el contrabando. Se ordenó su disolución oficial el 10/03/1785.',
                'effect' => 'Mientras esta carta permanezca boca arriba en el campo, no hay límites en el número de cartas en las manos de ambos jugadores.',
            ],
            [
                'deck' => '2',
                'card_id' => '21',
                'name' => 'Fusilamiento de Piar',
                'type' => 'trap',
                'stars' => 0,
                'monster_type' => 'trap',
                'new_monster_type' => 'trap',
                'attack' => 0,
                'defense' => 0,
                'description' => 'La rebeldía de Piar en contra de Bolívar y sus pretenciones por asumir el mando supremo llevaron al Libertador a ordenar su arresto. Fue prisionero en Aragua de Maturín y su fusilamiento se efectuó el 15 de agosto de 1817.',
                'effect' => 'Al atacar esta carta se invoca su terrible efecto que destruye todas las cartas mágicas y trampa que se encuentran en el campo de su oponente.',
            ],
            [
                'deck' => '2',
                'card_id' => '22',
                'name' => 'La Inmigración a Oriente',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Episodio de nuestra gesta emancipadora ocurrido el 7 de julio de 1814, en el que un gran número de personas de la sociedad caraqueña emigró hacia el oriente del país debido a los ataques realistas.',
                'effect' => 'Aumenta 500 puntos el ATQ de los realistas, disminuye 1000 puntos la DEF de su oponente y 200 puntos de vida por cada carta que esté en posición de DEF.',
            ],
            [
                'deck' => '2',
                'card_id' => '23',
                'name' => 'Boves Toma Valencia',
                'type' => 'trap',
                'stars' => 0,
                'monster_type' => 'trap',
                'new_monster_type' => 'trap',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Boves, tristemente célebre por sus crueldades durante la Guerra de Independencia toma Valencia el 10-07-1814. Reunió a todos los hombres y los asesinó. Esto duró varias noches.',
                'effect' => 'Elimine los puntos de DEF de todaslas cartas de su oponente durante un turno y atáquelo como usted quiera.',
            ],
            [
                'deck' => '2',
                'card_id' => '24',
                'name' => 'Monteverde Domingo',
                'type' => 'fire',
                'stars' => 7,
                'monster_type' => 'Soldado',
                'new_monster_type' => 'warrior',
                'attack' => 2500,
                'defense' => 2500,
                'description' => '(1772 - 1832) Natural de Tenerife, Islas Canarias. Logró la capitulación de Miranda ante sus fuerzas, la que incumplió inmediatamente. Se dedicó a matar a los jefes republicanos y confiscó parte de sus bienes.',
                'effect' => '',
            ],
            [
                'deck' => '2',
                'card_id' => '25',
                'name' => 'Rey Fernando VII',
                'type' => 'trap',
                'stars' => 0,
                'monster_type' => 'trap',
                'new_monster_type' => 'trap',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Nació el 14-10-1784. Abdicó el trono en favor del hermano de Napoleón Bonaparte. Al volver a España, retorna al poder e instaura una Monarquía Absoluta. No supo remediar la independencia que las colonias americanas habían proclamado.',
                'effect' => 'Lance un dado y multiplique por 200 el número obtenido y luego, sume el resultado a sus puntos de vida.',
            ],
            [
                'deck' => '2',
                'card_id' => '26',
                'name' => 'El Terrible Año 1814',
                'type' => 'fire',
                'stars' => 0,
                'monster_type' => 'trap',
                'new_monster_type' => 'trap',
                'attack' => 0,
                'defense' => 0,
                'description' => 'La República fue destruida por los realistas. El satánico plan de Boves consistió en fomentar la guerra de clases entre los patriotas para acabar con los blancos. De esta manera, boves priva a la República de sus dirigentes más notables y socava así los interes de la causa libertadora.',
                'effect' => 'Esta carta elimina todas las fusiones que se encuentren en el campo de su oponente y le permite enviar una de las cartas fusionadas al Cementerio.',
            ],
            [
                'deck' => '2',
                'card_id' => '27',
                'name' => 'Vicente Emparan',
                'type' => 'water',
                'stars' => 6,
                'monster_type' => 'Marino',
                'new_monster_type' => 'warrior',
                'attack' => 2000,
                'defense' => 2000,
                'description' => '(1750 - 1815) Marino español, nombrado Capitán General de Venezuela. Fue destituido de su cargo el 19 de Abril de 1810.',
                'effect' => 'Escoja una de las cartas del mazo de su oponente y colóquela bajo su control. Esto aumentará 500 puntos a la vida de su oponente.',
            ],
            [
                'deck' => '2',
                'card_id' => '29',
                'name' => 'Francisco Rosete',
                'type' => 'fire',
                'stars' => 7,
                'monster_type' => 'Oficial',
                'new_monster_type' => 'warrior',
                'attack' => 3000,
                'defense' => 3000,
                'description' => 'Cruel jefe realista. Ocupa Ocumare de Tuy y asesina a la población. Esto constituyó uno de los hechos más sangrientos de nuestra historia. Murió en la batalla de Juncal el 27-09-1816.',
                'effect' => 'Si al atacar con esta carta usted resulta vencedor, sume a sus puntos de vida el daño que le haya infligido su oponente.',
            ],
            [
                'deck' => '2',
                'card_id' => '29',
                'name' => 'Fray Bartolomé de las Casas',
                'type' => 'fire',
                'stars' => 5,
                'monster_type' => 'Sacerdote',
                'new_monster_type' => 'monk',
                'attack' => 1500,
                'defense' => 1000,
                'description' => 'Nació en Sevilla en 1475. Murió en 1566. Acompaño a Colón en su tercer viaje. Se hizo sacerdote y se dedicó a la defensa de los indios. Fue llamado El Apóstol de los Indios',
                'effect' => '',
            ],
            [
                'deck' => '2',
                'card_id' => '30',
                'name' => 'Obispo Rodrigo de Bastidas',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => '(1498 - 1571) Primer obispo de Venezuela. Fue enviado a Coro por la Corona española para que asumiera el cargo de obispo y gobernador y así poner fin a las disputas entre los conquistadores y colonos.',
                'effect' => 'Lance una moneda. Si cae cara usted debe atacar a su oponente con una carta que él escoja de las que estén boca abajo en su campo; si cae sello su oponente debe hacer lo mismo.',
            ],
            [
                'deck' => '2',
                'card_id' => '31',
                'name' => 'La Cosiata',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Movimiento separatista de la Gran Colombia iniciado en Valencia y Caracas en el año de 1826. Tuvo como líder al general José Antonio Páez.',
                'effect' => 'Esta carta disuelve todas las fusiones en el campo de batalla tanto las suyas como las de su oponente. Esto inflige un daño directo a los puntos de vida de su oponente de 1000 puntos.',
            ],
            [
                'deck' => '2',
                'card_id' => '32',
                'name' => 'Regulación de la Guerra',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Armisticio firmado el 25 de noviembre de 1820 en Trujillo por representantes de los gobiernos de España y Colombia con el objetivo de ponerle fin a la guerra.',
                'effect' => 'Esta carta le permite seleccionar y controlar una carta de su oponente sin importar su posición en el campo hasta el final del turno.',
            ],
            [
                'deck' => '2',
                'card_id' => '33',
                'name' => 'Batalla de Maturín',
                'type' => 'fire',
                'stars' => 8,
                'monster_type' => 'Batalla',
                'new_monster_type' => 'event',
                'attack' => 3500,
                'defense' => 3250,
                'description' => '11 de diciembre de 1814. El coronel Morales se hizo reconocer como sucesor de Boves y marchó sobre Maturín en busca de Ribas y Bermúdez. En el ataque final arrolló a los patriotas. Después del triunfo hubo una espantosa carnicería. Con esta batalla Morales dio el golpe final a la Segunda República.',
                'effect' => 'Con esta carta usted puede obtener el poder de la carta de Boves si la carta está en el Cementerio. Luego, sume el ATQ y DEF de ambas cartas.',
            ],
            [
                'deck' => '2',
                'card_id' => '34',
                'name' => 'La Encomienda',
                'type' => 'magic',
                'stars' => 0,
                'monster_type' => 'magic',
                'new_monster_type' => 'magic',
                'attack' => 0,
                'defense' => 0,
                'description' => 'Fue la manera ideada por los conquistadores para controlar y explotar la mano de obraindígena con el fin de asegurar algún tipo de producción: agrícola, perlífera, minera, artesanal o pecuaria. La Corona mantuvo esta institución por 200 años.',
                'effect' => 'Esta carta le permite tomar todas las cartas tipo indio que se encuentren en el campo o en manos de su oponente y ponerlas bajo su control.',
            ],
        ];

        foreach ($cards as $card) {
            DB::table('independencia_cards')->insert([
                'id' => (string) Str::uuid(),
                'deck' => $card['deck'],
                'card_id' => $card['card_id'],
                'name' => $card['name'],
                'type' => $card['type'],
                'stars' => $card['stars'],
                'monster_type' => $card['monster_type'],
                'new_monster_type' => $card['new_monster_type'],
                'attack' => $card['attack'],
                'defense' => $card['defense'],
                'description' => $card['description'],
                'effect' => $card['effect'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('independencia_cards');
    }
};
